// Generated by scripts/build-kana-pairs-data.mjs from data/kana-pairs.json — do not edit by hand.

export type KanaPairType = '촉음' | '장음' | '요음'

// 최소대립쌍 한 문제: 뜻(meaningKr)만 보고 올바른 표기(word)를 variants 속에서 고른다.
export interface KanaPair {
  id: string
  word: string
  meaningKr: string
  variants: string[]
  type: KanaPairType
}

export const kanaPairList: KanaPair[] = [
  {
    "id": "KP-1",
    "word": "きって",
    "meaningKr": "우표",
    "variants": [
      "きて",
      "きいて"
    ],
    "type": "촉음"
  },
  {
    "id": "KP-2",
    "word": "きっぷ",
    "meaningKr": "표(승차권)",
    "variants": [
      "きぷ",
      "きいぷ"
    ],
    "type": "촉음"
  },
  {
    "id": "KP-3",
    "word": "がっこう",
    "meaningKr": "학교",
    "variants": [
      "がこう",
      "がっこ"
    ],
    "type": "촉음"
  },
  {
    "id": "KP-4",
    "word": "けっこん",
    "meaningKr": "결혼",
    "variants": [
      "けこん",
      "けっこ"
    ],
    "type": "촉음"
  },
  {
    "id": "KP-5",
    "word": "ざっし",
    "meaningKr": "잡지",
    "variants": [
      "ざし",
      "ざっしい"
    ],
    "type": "촉음"
  },
  {
    "id": "KP-6",
    "word": "ちょっと",
    "meaningKr": "잠깐·조금",
    "variants": [
      "ちょと",
      "ちょっとう"
    ],
    "type": "촉음"
  },
  {
    "id": "KP-7",
    "word": "しっぱい",
    "meaningKr": "실패",
    "variants": [
      "しぱい",
      "しっぱ"
    ],
    "type": "촉음"
  },
  {
    "id": "KP-8",
    "word": "きっさてん",
    "meaningKr": "찻집",
    "variants": [
      "きさてん",
      "きっさて"
    ],
    "type": "촉음"
  },
  {
    "id": "KP-9",
    "word": "ビール",
    "meaningKr": "맥주",
    "variants": [
      "ビル",
      "ビイル"
    ],
    "type": "장음"
  },
  {
    "id": "KP-10",
    "word": "コーヒー",
    "meaningKr": "커피",
    "variants": [
      "コヒー",
      "コーヒ"
    ],
    "type": "장음"
  },
  {
    "id": "KP-11",
    "word": "おばあさん",
    "meaningKr": "할머니",
    "variants": [
      "おばさん",
      "おばーさん"
    ],
    "type": "장음"
  },
  {
    "id": "KP-12",
    "word": "おじいさん",
    "meaningKr": "할아버지",
    "variants": [
      "おじさん",
      "おじーさん"
    ],
    "type": "장음"
  },
  {
    "id": "KP-13",
    "word": "ゆうき",
    "meaningKr": "용기(勇気)",
    "variants": [
      "ゆき",
      "ゆうきい"
    ],
    "type": "장음"
  },
  {
    "id": "KP-14",
    "word": "くうき",
    "meaningKr": "공기",
    "variants": [
      "くき",
      "くうきい"
    ],
    "type": "장음"
  },
  {
    "id": "KP-15",
    "word": "こうこう",
    "meaningKr": "고등학교",
    "variants": [
      "ここう",
      "こうこ"
    ],
    "type": "장음"
  },
  {
    "id": "KP-16",
    "word": "せんせい",
    "meaningKr": "선생님",
    "variants": [
      "せんせ",
      "せえんせい"
    ],
    "type": "장음"
  },
  {
    "id": "KP-17",
    "word": "びょういん",
    "meaningKr": "병원",
    "variants": [
      "びよういん",
      "びょいん"
    ],
    "type": "요음"
  },
  {
    "id": "KP-18",
    "word": "きょう",
    "meaningKr": "오늘",
    "variants": [
      "きよう",
      "きょお"
    ],
    "type": "요음"
  },
  {
    "id": "KP-19",
    "word": "じゅう",
    "meaningKr": "십(10)",
    "variants": [
      "じゆう",
      "じゅ"
    ],
    "type": "요음"
  },
  {
    "id": "KP-20",
    "word": "りょこう",
    "meaningKr": "여행",
    "variants": [
      "りよこう",
      "りょこ"
    ],
    "type": "요음"
  },
  {
    "id": "KP-21",
    "word": "しゃしん",
    "meaningKr": "사진",
    "variants": [
      "しやしん",
      "しゃし"
    ],
    "type": "요음"
  },
  {
    "id": "KP-22",
    "word": "じょうず",
    "meaningKr": "능숙함·잘함",
    "variants": [
      "じようず",
      "じょず"
    ],
    "type": "요음"
  },
  {
    "id": "KP-23",
    "word": "にっき",
    "meaningKr": "일기",
    "variants": [
      "にき",
      "にっきい"
    ],
    "type": "촉음"
  },
  {
    "id": "KP-24",
    "word": "せっけん",
    "meaningKr": "비누",
    "variants": [
      "せけん",
      "せっけえ"
    ],
    "type": "촉음"
  },
  {
    "id": "KP-25",
    "word": "しゅっぱつ",
    "meaningKr": "출발",
    "variants": [
      "しゅぱつ",
      "しゅっぱ"
    ],
    "type": "촉음"
  },
  {
    "id": "KP-26",
    "word": "けってい",
    "meaningKr": "결정",
    "variants": [
      "けてい",
      "けってえ"
    ],
    "type": "촉음"
  },
  {
    "id": "KP-27",
    "word": "とおり",
    "meaningKr": "길·거리",
    "variants": [
      "とり",
      "とうり"
    ],
    "type": "장음"
  },
  {
    "id": "KP-28",
    "word": "すうがく",
    "meaningKr": "수학",
    "variants": [
      "すがく",
      "すうがくう"
    ],
    "type": "장음"
  },
  {
    "id": "KP-29",
    "word": "くうこう",
    "meaningKr": "공항",
    "variants": [
      "くこう",
      "くうこ"
    ],
    "type": "장음"
  },
  {
    "id": "KP-30",
    "word": "ほうそう",
    "meaningKr": "방송",
    "variants": [
      "ほそう",
      "ほうそ"
    ],
    "type": "장음"
  },
  {
    "id": "KP-31",
    "word": "かいしゃ",
    "meaningKr": "회사",
    "variants": [
      "かいしや",
      "かいしゃあ"
    ],
    "type": "요음"
  },
  {
    "id": "KP-32",
    "word": "じゅぎょう",
    "meaningKr": "수업",
    "variants": [
      "じゅぎよう",
      "じゆぎょう"
    ],
    "type": "요음"
  },
  {
    "id": "KP-33",
    "word": "りょかん",
    "meaningKr": "여관",
    "variants": [
      "りよかん",
      "りょか"
    ],
    "type": "요음"
  },
  {
    "id": "KP-34",
    "word": "じょうだん",
    "meaningKr": "농담",
    "variants": [
      "じよだん",
      "じょだん"
    ],
    "type": "요음"
  }
]
