// Generated by scripts/build-radical-data.mjs from data/radicals.json — do not edit by hand.
import type { KanjiLevel } from './kanji'

export type RadicalMeaningSource = 'kanji-data' | 'wiktionary' | 'generated-uncertain'

export interface Radical {
  number: number
  strokeCount: number
  radical: string
  meaningEn: string
  meaningKr: string
  meaningKrSource: RadicalMeaningSource
  // lowest JLPT level among jouyou kanji using this as their classical
  // radical (kanjidic2-derived) — see scripts/add-radical-levels.mjs
  level: KanjiLevel
}

export const radicalList: Radical[] = [
  {
    "number": 1,
    "strokeCount": 1,
    "radical": "一",
    "meaningEn": "one",
    "meaningKr": "하나 일",
    "level": "N5",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 2,
    "strokeCount": 1,
    "radical": "丨",
    "meaningEn": "line",
    "meaningKr": "뚫을 곤",
    "meaningKrSource": "wiktionary",
    "level": "N5"
  },
  {
    "number": 3,
    "strokeCount": 1,
    "radical": "丶",
    "meaningEn": "dot",
    "meaningKr": "점 주",
    "meaningKrSource": "wiktionary",
    "level": "N4"
  },
  {
    "number": 4,
    "strokeCount": 1,
    "radical": "丿",
    "meaningEn": "slash",
    "meaningKr": "삐침 별",
    "meaningKrSource": "wiktionary",
    "level": "N3"
  },
  {
    "number": 5,
    "strokeCount": 1,
    "radical": "乙",
    "meaningEn": "second",
    "meaningKr": "새 을",
    "level": "N5",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 6,
    "strokeCount": 1,
    "radical": "亅",
    "meaningEn": "hook",
    "meaningKr": "갈고리 궐",
    "meaningKrSource": "wiktionary",
    "level": "N4"
  },
  {
    "number": 7,
    "strokeCount": 2,
    "radical": "二",
    "meaningEn": "two",
    "meaningKr": "둘 이",
    "level": "N5",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 8,
    "strokeCount": 2,
    "radical": "亠",
    "meaningEn": "lid",
    "meaningKr": "돼지해머리 두",
    "meaningKrSource": "wiktionary",
    "level": "N4"
  },
  {
    "number": 9,
    "strokeCount": 2,
    "radical": "人",
    "meaningEn": "man",
    "meaningKr": "사람 인",
    "level": "N5",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 10,
    "strokeCount": 2,
    "radical": "儿",
    "meaningEn": "son, legs",
    "meaningKr": "어진사람 인",
    "meaningKrSource": "wiktionary",
    "level": "N5"
  },
  {
    "number": 11,
    "strokeCount": 2,
    "radical": "入",
    "meaningEn": "enter",
    "meaningKr": "들 입",
    "level": "N5",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 12,
    "strokeCount": 2,
    "radical": "八",
    "meaningEn": "eight",
    "meaningKr": "여덟 팔",
    "level": "N5",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 13,
    "strokeCount": 2,
    "radical": "冂",
    "meaningEn": "wide",
    "meaningKr": "멀 경",
    "meaningKrSource": "wiktionary",
    "level": "N5"
  },
  {
    "number": 14,
    "strokeCount": 2,
    "radical": "冖",
    "meaningEn": "cloth cover",
    "meaningKr": "덮을 멱",
    "meaningKrSource": "wiktionary",
    "level": "N4"
  },
  {
    "number": 15,
    "strokeCount": 2,
    "radical": "冫",
    "meaningEn": "ice",
    "meaningKr": "얼음 빙",
    "meaningKrSource": "wiktionary",
    "level": "N4"
  },
  {
    "number": 16,
    "strokeCount": 2,
    "radical": "几",
    "meaningEn": "table",
    "meaningKr": "안석 궤",
    "meaningKrSource": "wiktionary",
    "level": "N3"
  },
  {
    "number": 17,
    "strokeCount": 2,
    "radical": "凵",
    "meaningEn": "receptacle",
    "meaningKr": "입 벌릴 감",
    "meaningKrSource": "wiktionary",
    "level": "N5"
  },
  {
    "number": 18,
    "strokeCount": 2,
    "radical": "刀",
    "meaningEn": "knife",
    "meaningKr": "칼 도",
    "level": "N5",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 19,
    "strokeCount": 2,
    "radical": "力",
    "meaningEn": "power",
    "meaningKr": "힘 력",
    "level": "N4",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 20,
    "strokeCount": 2,
    "radical": "勹",
    "meaningEn": "wrap",
    "meaningKr": "쌀 포",
    "meaningKrSource": "wiktionary",
    "level": "N2"
  },
  {
    "number": 21,
    "strokeCount": 2,
    "radical": "匕",
    "meaningEn": "spoon",
    "meaningKr": "비수 비",
    "meaningKrSource": "wiktionary",
    "level": "N5"
  },
  {
    "number": 22,
    "strokeCount": 2,
    "radical": "匚",
    "meaningEn": "box",
    "meaningKr": "상자 방",
    "meaningKrSource": "wiktionary",
    "level": "N1"
  },
  {
    "number": 23,
    "strokeCount": 2,
    "radical": "匸",
    "meaningEn": "hiding enclosure",
    "meaningKr": "감출 혜",
    "meaningKrSource": "wiktionary",
    "level": "N4"
  },
  {
    "number": 24,
    "strokeCount": 2,
    "radical": "十",
    "meaningEn": "ten",
    "meaningKr": "열 십",
    "level": "N5",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 25,
    "strokeCount": 2,
    "radical": "卜",
    "meaningEn": "divination",
    "meaningKr": "점 복",
    "meaningKrSource": "wiktionary",
    "level": "N2"
  },
  {
    "number": 26,
    "strokeCount": 2,
    "radical": "卩",
    "meaningEn": "seal device",
    "meaningKr": "병부 절",
    "meaningKrSource": "wiktionary",
    "level": "N3"
  },
  {
    "number": 27,
    "strokeCount": 2,
    "radical": "厂",
    "meaningEn": "cliff",
    "meaningKr": "기슭 엄",
    "meaningKrSource": "wiktionary",
    "level": "N3"
  },
  {
    "number": 28,
    "strokeCount": 2,
    "radical": "厶",
    "meaningEn": "private",
    "meaningKr": "사사 사",
    "meaningKrSource": "wiktionary",
    "level": "N4"
  },
  {
    "number": 29,
    "strokeCount": 2,
    "radical": "又",
    "meaningEn": "again",
    "meaningKr": "또 우",
    "level": "N5",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 30,
    "strokeCount": 3,
    "radical": "口",
    "meaningEn": "mouth",
    "meaningKr": "입 구",
    "level": "N5",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 31,
    "strokeCount": 3,
    "radical": "囗",
    "meaningEn": "enclosure",
    "meaningKr": "에울 위",
    "meaningKrSource": "wiktionary",
    "level": "N5"
  },
  {
    "number": 32,
    "strokeCount": 3,
    "radical": "土",
    "meaningEn": "earth",
    "meaningKr": "흙 토",
    "level": "N5",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 33,
    "strokeCount": 3,
    "radical": "士",
    "meaningEn": "scholar",
    "meaningKr": "선비 사",
    "level": "N4",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 34,
    "strokeCount": 3,
    "radical": "夂",
    "meaningEn": "go",
    "meaningKr": "뒤져올 치",
    "meaningKrSource": "wiktionary",
    "level": "N3"
  },
  {
    "number": 35,
    "strokeCount": 3,
    "radical": "夊",
    "meaningEn": "go slowly",
    "meaningKr": "천천히 걸을 쇠",
    "meaningKrSource": "wiktionary",
    "level": "N4"
  },
  {
    "number": 36,
    "strokeCount": 3,
    "radical": "夕",
    "meaningEn": "evening",
    "meaningKr": "저녁 석",
    "level": "N5",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 37,
    "strokeCount": 3,
    "radical": "大",
    "meaningEn": "big",
    "meaningKr": "큰 대",
    "level": "N5",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 38,
    "strokeCount": 3,
    "radical": "女",
    "meaningEn": "woman",
    "meaningKr": "계집 녀",
    "level": "N5",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 39,
    "strokeCount": 3,
    "radical": "子",
    "meaningEn": "child",
    "meaningKr": "아들 자",
    "level": "N5",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 40,
    "strokeCount": 3,
    "radical": "宀",
    "meaningEn": "roof",
    "meaningKr": "집 면",
    "meaningKrSource": "wiktionary",
    "level": "N4"
  },
  {
    "number": 41,
    "strokeCount": 3,
    "radical": "寸",
    "meaningEn": "inch",
    "meaningKr": "마디 촌",
    "level": "N3",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 42,
    "strokeCount": 3,
    "radical": "小",
    "meaningEn": "small",
    "meaningKr": "작을 소",
    "level": "N5",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 43,
    "strokeCount": 3,
    "radical": "尢",
    "meaningEn": "lame",
    "meaningKr": "절름발이 왕",
    "meaningKrSource": "wiktionary",
    "level": "N1"
  },
  {
    "number": 44,
    "strokeCount": 3,
    "radical": "尸",
    "meaningEn": "corpse",
    "meaningKr": "주검 시",
    "level": "N4",
    "meaningKrSource": "generated-uncertain"
  },
  {
    "number": 45,
    "strokeCount": 3,
    "radical": "屮",
    "meaningEn": "sprout",
    "meaningKr": "왼손 좌",
    "meaningKrSource": "wiktionary",
    "level": "N1"
  },
  {
    "number": 46,
    "strokeCount": 3,
    "radical": "山",
    "meaningEn": "mountain",
    "meaningKr": "뫼 산",
    "level": "N5",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 47,
    "strokeCount": 3,
    "radical": "巛",
    "meaningEn": "river",
    "meaningKr": "내 천",
    "meaningKrSource": "wiktionary",
    "level": "N5"
  },
  {
    "number": 48,
    "strokeCount": 3,
    "radical": "工",
    "meaningEn": "work",
    "meaningKr": "장인 공",
    "level": "N5",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 49,
    "strokeCount": 3,
    "radical": "己",
    "meaningEn": "oneself",
    "meaningKr": "몸 기",
    "level": "N2",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 50,
    "strokeCount": 3,
    "radical": "巾",
    "meaningEn": "turban",
    "meaningKr": "수건 건",
    "level": "N4",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 51,
    "strokeCount": 3,
    "radical": "干",
    "meaningEn": "dry",
    "meaningKr": "방패 간",
    "level": "N5",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 52,
    "strokeCount": 3,
    "radical": "幺",
    "meaningEn": "short thread",
    "meaningKr": "작을 요",
    "meaningKrSource": "wiktionary",
    "level": "N3"
  },
  {
    "number": 53,
    "strokeCount": 3,
    "radical": "广",
    "meaningEn": "dotted cliff",
    "meaningKr": "집 엄",
    "meaningKrSource": "wiktionary",
    "level": "N4"
  },
  {
    "number": 54,
    "strokeCount": 3,
    "radical": "廴",
    "meaningEn": "long stride",
    "meaningKr": "길게 걸을 인",
    "meaningKrSource": "wiktionary",
    "level": "N4"
  },
  {
    "number": 55,
    "strokeCount": 3,
    "radical": "廾",
    "meaningEn": "arch",
    "meaningKr": "들 공",
    "meaningKrSource": "wiktionary",
    "level": "N1"
  },
  {
    "number": 56,
    "strokeCount": 3,
    "radical": "弋",
    "meaningEn": "shoot",
    "meaningKr": "주살 익",
    "meaningKrSource": "wiktionary",
    "level": "N3"
  },
  {
    "number": 57,
    "strokeCount": 3,
    "radical": "弓",
    "meaningEn": "bow",
    "meaningKr": "활 궁",
    "level": "N4",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 58,
    "strokeCount": 3,
    "radical": "彐",
    "meaningEn": "snout",
    "meaningKr": "돼지머리 계",
    "meaningKrSource": "wiktionary",
    "level": "N3"
  },
  {
    "number": 59,
    "strokeCount": 3,
    "radical": "彡",
    "meaningEn": "bristle",
    "meaningKr": "터럭 삼",
    "meaningKrSource": "wiktionary",
    "level": "N3"
  },
  {
    "number": 60,
    "strokeCount": 3,
    "radical": "彳",
    "meaningEn": "step",
    "meaningKr": "천천히 걸을 척",
    "meaningKrSource": "wiktionary",
    "level": "N5"
  },
  {
    "number": 61,
    "strokeCount": 4,
    "radical": "心",
    "meaningEn": "heart",
    "meaningKr": "마음 심",
    "level": "N4",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 62,
    "strokeCount": 4,
    "radical": "戈",
    "meaningEn": "halberd",
    "meaningKr": "창 과",
    "meaningKrSource": "wiktionary",
    "level": "N3"
  },
  {
    "number": 63,
    "strokeCount": 4,
    "radical": "戶",
    "meaningEn": "door",
    "meaningKr": "지게 호",
    "meaningKrSource": "wiktionary",
    "level": "N3"
  },
  {
    "number": 64,
    "strokeCount": 4,
    "radical": "手",
    "meaningEn": "hand",
    "meaningKr": "손 수",
    "level": "N4",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 65,
    "strokeCount": 4,
    "radical": "支",
    "meaningEn": "branch",
    "meaningKr": "지탱할 지",
    "level": "N3",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 66,
    "strokeCount": 4,
    "radical": "攴",
    "meaningEn": "rap, tap",
    "meaningKr": "칠 복",
    "meaningKrSource": "wiktionary",
    "level": "N4"
  },
  {
    "number": 67,
    "strokeCount": 4,
    "radical": "文",
    "meaningEn": "script",
    "meaningKr": "글 문",
    "level": "N4",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 68,
    "strokeCount": 4,
    "radical": "斗",
    "meaningEn": "dipper",
    "meaningKr": "말 두",
    "level": "N4",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 69,
    "strokeCount": 4,
    "radical": "斤",
    "meaningEn": "axe",
    "meaningKr": "도끼 근",
    "level": "N4",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 70,
    "strokeCount": 4,
    "radical": "方",
    "meaningEn": "square",
    "meaningKr": "모 방",
    "level": "N4",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 71,
    "strokeCount": 4,
    "radical": "无",
    "meaningEn": "not",
    "meaningKr": "없을 무",
    "meaningKrSource": "wiktionary",
    "level": "N1"
  },
  {
    "number": 72,
    "strokeCount": 4,
    "radical": "日",
    "meaningEn": "sun",
    "meaningKr": "날 일",
    "level": "N5",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 73,
    "strokeCount": 4,
    "radical": "曰",
    "meaningEn": "say",
    "meaningKr": "가로 왈",
    "meaningKrSource": "wiktionary",
    "level": "N5"
  },
  {
    "number": 74,
    "strokeCount": 4,
    "radical": "月",
    "meaningEn": "moon",
    "meaningKr": "달 월",
    "level": "N5",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 75,
    "strokeCount": 4,
    "radical": "木",
    "meaningEn": "tree",
    "meaningKr": "나무 목",
    "level": "N5",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 76,
    "strokeCount": 4,
    "radical": "欠",
    "meaningEn": "lack",
    "meaningKr": "이지러질 결",
    "level": "N4",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 77,
    "strokeCount": 4,
    "radical": "止",
    "meaningEn": "stop",
    "meaningKr": "그칠 지",
    "level": "N4",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 78,
    "strokeCount": 4,
    "radical": "歹",
    "meaningEn": "death",
    "meaningKr": "앙상한 뼈 알",
    "meaningKrSource": "wiktionary",
    "level": "N4"
  },
  {
    "number": 79,
    "strokeCount": 4,
    "radical": "殳",
    "meaningEn": "weapon",
    "meaningKr": "창 수",
    "meaningKrSource": "wiktionary",
    "level": "N3"
  },
  {
    "number": 80,
    "strokeCount": 4,
    "radical": "毋",
    "meaningEn": "do not",
    "meaningKr": "말 무",
    "meaningKrSource": "wiktionary",
    "level": "N5"
  },
  {
    "number": 81,
    "strokeCount": 4,
    "radical": "比",
    "meaningEn": "compare",
    "meaningKr": "견줄 비",
    "level": "N2",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 82,
    "strokeCount": 4,
    "radical": "毛",
    "meaningEn": "fur",
    "meaningKr": "털 모",
    "level": "N2",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 83,
    "strokeCount": 4,
    "radical": "氏",
    "meaningEn": "clan",
    "meaningKr": "성씨 씨",
    "level": "N3",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 84,
    "strokeCount": 4,
    "radical": "气",
    "meaningEn": "steam",
    "meaningKr": "기운 기",
    "meaningKrSource": "wiktionary",
    "level": "N5"
  },
  {
    "number": 85,
    "strokeCount": 4,
    "radical": "水",
    "meaningEn": "water",
    "meaningKr": "물 수",
    "level": "N5",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 86,
    "strokeCount": 4,
    "radical": "火",
    "meaningEn": "fire",
    "meaningKr": "불 화",
    "level": "N5",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 87,
    "strokeCount": 4,
    "radical": "爪",
    "meaningEn": "claw",
    "meaningKr": "손톱 조",
    "level": "N1",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 88,
    "strokeCount": 4,
    "radical": "父",
    "meaningEn": "father",
    "meaningKr": "아비 부",
    "level": "N5",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 89,
    "strokeCount": 4,
    "radical": "爻",
    "meaningEn": "trigrams",
    "meaningKr": "점괘 효",
    "meaningKrSource": "wiktionary",
    "level": "N1"
  },
  {
    "number": 90,
    "strokeCount": 4,
    "radical": "爿",
    "meaningEn": "split wood",
    "meaningKr": "널조각 장",
    "meaningKrSource": "wiktionary",
    "level": "N1"
  },
  {
    "number": 91,
    "strokeCount": 4,
    "radical": "片",
    "meaningEn": "slice",
    "meaningKr": "조각 편",
    "level": "N2",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 92,
    "strokeCount": 4,
    "radical": "牙",
    "meaningEn": "fang",
    "meaningKr": "어금니 아",
    "level": "N1",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 93,
    "strokeCount": 4,
    "radical": "牛",
    "meaningEn": "cow",
    "meaningKr": "소 우",
    "level": "N4",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 94,
    "strokeCount": 4,
    "radical": "犬",
    "meaningEn": "dog",
    "meaningKr": "개 견",
    "level": "N4",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 95,
    "strokeCount": 5,
    "radical": "玄",
    "meaningEn": "profound",
    "meaningKr": "검을 현",
    "level": "N1",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 96,
    "strokeCount": 5,
    "radical": "玉",
    "meaningEn": "jade",
    "meaningKr": "구슬 옥",
    "level": "N4",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 97,
    "strokeCount": 5,
    "radical": "瓜",
    "meaningEn": "melon",
    "meaningKr": "오이 과",
    "meaningKrSource": "wiktionary",
    "level": "N1"
  },
  {
    "number": 98,
    "strokeCount": 5,
    "radical": "瓦",
    "meaningEn": "tile",
    "meaningKr": "기와 와",
    "level": "N2",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 99,
    "strokeCount": 5,
    "radical": "甘",
    "meaningEn": "sweet",
    "meaningKr": "달다 감",
    "level": "N2",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 100,
    "strokeCount": 5,
    "radical": "生",
    "meaningEn": "life",
    "meaningKr": "날 생",
    "level": "N5",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 101,
    "strokeCount": 5,
    "radical": "用",
    "meaningEn": "use",
    "meaningKr": "쓸 용",
    "level": "N4",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 102,
    "strokeCount": 5,
    "radical": "田",
    "meaningEn": "field",
    "meaningKr": "밭 전",
    "level": "N5",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 103,
    "strokeCount": 5,
    "radical": "疋",
    "meaningEn": "bolt of cloth",
    "meaningKr": "필 필, 발 소",
    "meaningKrSource": "wiktionary",
    "level": "N3"
  },
  {
    "number": 104,
    "strokeCount": 5,
    "radical": "疒",
    "meaningEn": "sickness",
    "meaningKr": "병 들어 기댈 녁",
    "meaningKrSource": "wiktionary",
    "level": "N4"
  },
  {
    "number": 105,
    "strokeCount": 5,
    "radical": "癶",
    "meaningEn": "footsteps",
    "meaningKr": "등질 발",
    "meaningKrSource": "wiktionary",
    "level": "N4"
  },
  {
    "number": 106,
    "strokeCount": 5,
    "radical": "白",
    "meaningEn": "white",
    "meaningKr": "흰 백",
    "level": "N5",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 107,
    "strokeCount": 5,
    "radical": "皮",
    "meaningEn": "skin",
    "meaningKr": "가죽 피",
    "level": "N2",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 108,
    "strokeCount": 5,
    "radical": "皿",
    "meaningEn": "dish",
    "meaningKr": "접시 명",
    "level": "N3",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 109,
    "strokeCount": 5,
    "radical": "目",
    "meaningEn": "eye",
    "meaningKr": "눈 목",
    "level": "N4",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 110,
    "strokeCount": 5,
    "radical": "矛",
    "meaningEn": "spear",
    "meaningKr": "창 모",
    "level": "N1",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 111,
    "strokeCount": 5,
    "radical": "矢",
    "meaningEn": "arrow",
    "meaningKr": "화살 시",
    "level": "N4",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 112,
    "strokeCount": 5,
    "radical": "石",
    "meaningEn": "stone",
    "meaningKr": "돌 석",
    "level": "N4",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 113,
    "strokeCount": 5,
    "radical": "示",
    "meaningEn": "spirit",
    "meaningKr": "보일 시",
    "level": "N4",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 114,
    "strokeCount": 5,
    "radical": "禸",
    "meaningEn": "track",
    "meaningKr": "짐승 발자국 유",
    "meaningKrSource": "wiktionary",
    "level": "N1"
  },
  {
    "number": 115,
    "strokeCount": 5,
    "radical": "禾",
    "meaningEn": "grain",
    "meaningKr": "벼 화",
    "meaningKrSource": "wiktionary",
    "level": "N4"
  },
  {
    "number": 116,
    "strokeCount": 5,
    "radical": "穴",
    "meaningEn": "cave",
    "meaningKr": "구멍 혈",
    "level": "N4",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 117,
    "strokeCount": 5,
    "radical": "立",
    "meaningEn": "stand",
    "meaningKr": "설 립",
    "level": "N4",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 118,
    "strokeCount": 6,
    "radical": "竹",
    "meaningEn": "bamboo",
    "meaningKr": "대나무 죽",
    "level": "N4",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 119,
    "strokeCount": 6,
    "radical": "米",
    "meaningEn": "rice",
    "meaningKr": "쌀 미",
    "level": "N3",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 120,
    "strokeCount": 6,
    "radical": "糸",
    "meaningEn": "silk",
    "meaningKr": "실 사",
    "level": "N4",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 121,
    "strokeCount": 6,
    "radical": "缶",
    "meaningEn": "jar",
    "meaningKr": "장군 부",
    "level": "N2",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 122,
    "strokeCount": 6,
    "radical": "网",
    "meaningEn": "net",
    "meaningKr": "그물 망",
    "meaningKrSource": "wiktionary",
    "level": "N3"
  },
  {
    "number": 123,
    "strokeCount": 6,
    "radical": "羊",
    "meaningEn": "sheep",
    "meaningKr": "양 양",
    "level": "N3",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 124,
    "strokeCount": 6,
    "radical": "羽",
    "meaningEn": "feather",
    "meaningKr": "깃 우",
    "level": "N4",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 125,
    "strokeCount": 6,
    "radical": "老",
    "meaningEn": "old",
    "meaningKr": "늙을 로",
    "level": "N4",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 126,
    "strokeCount": 6,
    "radical": "而",
    "meaningEn": "and",
    "meaningKr": "말이을 이",
    "meaningKrSource": "wiktionary",
    "level": "N1"
  },
  {
    "number": 127,
    "strokeCount": 6,
    "radical": "耒",
    "meaningEn": "plough",
    "meaningKr": "쟁기 뢰",
    "meaningKrSource": "wiktionary",
    "level": "N2"
  },
  {
    "number": 128,
    "strokeCount": 6,
    "radical": "耳",
    "meaningEn": "ear",
    "meaningKr": "귀 이",
    "level": "N5",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 129,
    "strokeCount": 6,
    "radical": "聿",
    "meaningEn": "brush",
    "meaningKr": "붓 율",
    "meaningKrSource": "wiktionary",
    "level": "N1"
  },
  {
    "number": 130,
    "strokeCount": 6,
    "radical": "肉",
    "meaningEn": "meat",
    "meaningKr": "고기 육",
    "level": "N4",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 131,
    "strokeCount": 6,
    "radical": "臣",
    "meaningEn": "minister",
    "meaningKr": "신하 신",
    "level": "N2",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 132,
    "strokeCount": 6,
    "radical": "自",
    "meaningEn": "self",
    "meaningKr": "스스로 자",
    "level": "N4",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 133,
    "strokeCount": 6,
    "radical": "至",
    "meaningEn": "arrive",
    "meaningKr": "이르다 지",
    "level": "N1",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 134,
    "strokeCount": 6,
    "radical": "臼",
    "meaningEn": "mortar",
    "meaningKr": "절구 구",
    "level": "N1",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 135,
    "strokeCount": 6,
    "radical": "舌",
    "meaningEn": "tongue",
    "meaningKr": "혀 설",
    "level": "N1",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 136,
    "strokeCount": 6,
    "radical": "舛",
    "meaningEn": "oppose",
    "meaningKr": "어그러질 천",
    "meaningKrSource": "wiktionary",
    "level": "N3"
  },
  {
    "number": 137,
    "strokeCount": 6,
    "radical": "舟",
    "meaningEn": "boat",
    "meaningKr": "배 주",
    "level": "N3",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 138,
    "strokeCount": 6,
    "radical": "艮",
    "meaningEn": "stopping",
    "meaningKr": "괘이름 간",
    "meaningKrSource": "wiktionary",
    "level": "N3"
  },
  {
    "number": 139,
    "strokeCount": 6,
    "radical": "色",
    "meaningEn": "color",
    "meaningKr": "빛 색",
    "level": "N4",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 140,
    "strokeCount": 6,
    "radical": "艸",
    "meaningEn": "grass",
    "meaningKr": "풀 초",
    "meaningKrSource": "wiktionary",
    "level": "N4"
  },
  {
    "number": 141,
    "strokeCount": 6,
    "radical": "虍",
    "meaningEn": "tiger",
    "meaningKr": "범의 문채 호",
    "meaningKrSource": "wiktionary",
    "level": "N1"
  },
  {
    "number": 142,
    "strokeCount": 6,
    "radical": "虫",
    "meaningEn": "insect",
    "meaningKr": "벌레 훼",
    "level": "N2",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 143,
    "strokeCount": 6,
    "radical": "血",
    "meaningEn": "blood",
    "meaningKr": "피 혈",
    "level": "N2",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 144,
    "strokeCount": 6,
    "radical": "行",
    "meaningEn": "walk enclosure",
    "meaningKr": "다닐 행",
    "level": "N5",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 145,
    "strokeCount": 6,
    "radical": "衣",
    "meaningEn": "clothes",
    "meaningKr": "옷 의",
    "level": "N3",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 146,
    "strokeCount": 6,
    "radical": "襾",
    "meaningEn": "cover",
    "meaningKr": "덮을 아",
    "meaningKrSource": "wiktionary",
    "level": "N5"
  },
  {
    "number": 147,
    "strokeCount": 7,
    "radical": "見",
    "meaningEn": "see",
    "meaningKr": "볼 견",
    "level": "N5",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 148,
    "strokeCount": 7,
    "radical": "角",
    "meaningEn": "horn",
    "meaningKr": "뿔 각",
    "level": "N3",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 149,
    "strokeCount": 7,
    "radical": "言",
    "meaningEn": "speech",
    "meaningKr": "말씀 언",
    "level": "N5",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 150,
    "strokeCount": 7,
    "radical": "谷",
    "meaningEn": "valley",
    "meaningKr": "골 곡",
    "level": "N2",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 151,
    "strokeCount": 7,
    "radical": "豆",
    "meaningEn": "bean",
    "meaningKr": "콩 두",
    "level": "N2",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 152,
    "strokeCount": 7,
    "radical": "豕",
    "meaningEn": "pig",
    "meaningKr": "돼지 시",
    "meaningKrSource": "wiktionary",
    "level": "N2"
  },
  {
    "number": 153,
    "strokeCount": 7,
    "radical": "豸",
    "meaningEn": "badger",
    "meaningKr": "발 없는 벌레 치",
    "meaningKrSource": "wiktionary",
    "level": "N1"
  },
  {
    "number": 154,
    "strokeCount": 7,
    "radical": "貝",
    "meaningEn": "shell",
    "meaningKr": "조개 패",
    "level": "N4",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 155,
    "strokeCount": 7,
    "radical": "赤",
    "meaningEn": "red",
    "meaningKr": "붉을 적",
    "level": "N4",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 156,
    "strokeCount": 7,
    "radical": "走",
    "meaningEn": "run",
    "meaningKr": "달릴 주",
    "level": "N4",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 157,
    "strokeCount": 7,
    "radical": "足",
    "meaningEn": "foot",
    "meaningKr": "발 족",
    "level": "N4",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 158,
    "strokeCount": 7,
    "radical": "身",
    "meaningEn": "body",
    "meaningKr": "몸 신",
    "level": "N1",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 159,
    "strokeCount": 7,
    "radical": "車",
    "meaningEn": "cart",
    "meaningKr": "수레 차",
    "level": "N5",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 160,
    "strokeCount": 7,
    "radical": "辛",
    "meaningEn": "bitter",
    "meaningKr": "맵다 신",
    "level": "N3",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 161,
    "strokeCount": 7,
    "radical": "辰",
    "meaningEn": "morning",
    "meaningKr": "다섯째 지지 진",
    "meaningKrSource": "wiktionary",
    "level": "N2"
  },
  {
    "number": 162,
    "strokeCount": 7,
    "radical": "辵",
    "meaningEn": "walk",
    "meaningKr": "쉬엄쉬엄 갈 착",
    "meaningKrSource": "wiktionary",
    "level": "N4"
  },
  {
    "number": 163,
    "strokeCount": 7,
    "radical": "邑",
    "meaningEn": "city",
    "meaningKr": "고을 읍",
    "meaningKrSource": "wiktionary",
    "level": "N3"
  },
  {
    "number": 164,
    "strokeCount": 7,
    "radical": "酉",
    "meaningEn": "wine",
    "meaningKr": "열째 지지 유",
    "meaningKrSource": "wiktionary",
    "level": "N3"
  },
  {
    "number": 165,
    "strokeCount": 7,
    "radical": "釆",
    "meaningEn": "distinguish",
    "meaningKr": "분별할 변",
    "meaningKrSource": "wiktionary",
    "level": "N1"
  },
  {
    "number": 166,
    "strokeCount": 7,
    "radical": "里",
    "meaningEn": "village",
    "meaningKr": "마을 리",
    "level": "N4",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 167,
    "strokeCount": 8,
    "radical": "金",
    "meaningEn": "gold",
    "meaningKr": "쇠 금",
    "level": "N5",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 168,
    "strokeCount": 8,
    "radical": "長",
    "meaningEn": "long",
    "meaningKr": "길 장",
    "level": "N5",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 169,
    "strokeCount": 8,
    "radical": "門",
    "meaningEn": "gate",
    "meaningKr": "문 문",
    "level": "N5",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 170,
    "strokeCount": 8,
    "radical": "阜",
    "meaningEn": "mound",
    "meaningKr": "언덕 부",
    "level": "N4",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 171,
    "strokeCount": 8,
    "radical": "隶",
    "meaningEn": "slave",
    "meaningKr": "미칠 이",
    "meaningKrSource": "wiktionary",
    "level": "N1"
  },
  {
    "number": 172,
    "strokeCount": 8,
    "radical": "隹",
    "meaningEn": "short-tailed bird",
    "meaningKr": "새 추",
    "meaningKrSource": "wiktionary",
    "level": "N4"
  },
  {
    "number": 173,
    "strokeCount": 8,
    "radical": "雨",
    "meaningEn": "rain",
    "meaningKr": "비 우",
    "level": "N5",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 174,
    "strokeCount": 8,
    "radical": "靑",
    "meaningEn": "blue",
    "meaningKr": "푸를 청",
    "meaningKrSource": "wiktionary",
    "level": "N4"
  },
  {
    "number": 175,
    "strokeCount": 8,
    "radical": "非",
    "meaningEn": "wrong",
    "meaningKr": "아닐 비",
    "level": "N3",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 176,
    "strokeCount": 9,
    "radical": "面",
    "meaningEn": "face",
    "meaningKr": "낯 면",
    "level": "N3",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 177,
    "strokeCount": 9,
    "radical": "革",
    "meaningEn": "leather",
    "meaningKr": "가죽 혁",
    "level": "N3",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 178,
    "strokeCount": 9,
    "radical": "韋",
    "meaningEn": "tanned leather",
    "meaningKr": "무두질한 가죽 위",
    "meaningKrSource": "wiktionary",
    "level": "N1"
  },
  {
    "number": 179,
    "strokeCount": 9,
    "radical": "韭",
    "meaningEn": "leek",
    "meaningKr": "부추 구",
    "meaningKrSource": "wiktionary",
    "level": "N1"
  },
  {
    "number": 180,
    "strokeCount": 9,
    "radical": "音",
    "meaningEn": "sound",
    "meaningKr": "소리 음",
    "level": "N4",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 181,
    "strokeCount": 9,
    "radical": "頁",
    "meaningEn": "leaf",
    "meaningKr": "머리 혈",
    "meaningKrSource": "wiktionary",
    "level": "N4"
  },
  {
    "number": 182,
    "strokeCount": 9,
    "radical": "風",
    "meaningEn": "wind",
    "meaningKr": "바람 풍",
    "level": "N4",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 183,
    "strokeCount": 9,
    "radical": "飛",
    "meaningEn": "fly",
    "meaningKr": "날 비",
    "level": "N3",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 184,
    "strokeCount": 9,
    "radical": "食",
    "meaningEn": "eat",
    "meaningKr": "먹을 식",
    "level": "N5",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 185,
    "strokeCount": 9,
    "radical": "首",
    "meaningEn": "head",
    "meaningKr": "머리 수",
    "level": "N3",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 186,
    "strokeCount": 9,
    "radical": "香",
    "meaningEn": "fragrant",
    "meaningKr": "향기 향",
    "level": "N2",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 187,
    "strokeCount": 10,
    "radical": "馬",
    "meaningEn": "horse",
    "meaningKr": "말 마",
    "level": "N4",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 188,
    "strokeCount": 10,
    "radical": "骨",
    "meaningEn": "bone",
    "meaningKr": "뼈 골",
    "level": "N2",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 189,
    "strokeCount": 10,
    "radical": "高",
    "meaningEn": "tall",
    "meaningKr": "높을 고",
    "level": "N5",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 190,
    "strokeCount": 10,
    "radical": "髟",
    "meaningEn": "hair",
    "meaningKr": "머리털 드리워질 표",
    "meaningKrSource": "wiktionary",
    "level": "N3"
  },
  {
    "number": 191,
    "strokeCount": 10,
    "radical": "鬥",
    "meaningEn": "fight",
    "meaningKr": "싸울 두",
    "meaningKrSource": "wiktionary",
    "level": "N1"
  },
  {
    "number": 192,
    "strokeCount": 10,
    "radical": "鬯",
    "meaningEn": "sacrificial wine",
    "meaningKr": "울창주 창",
    "meaningKrSource": "wiktionary",
    "level": "N1"
  },
  {
    "number": 193,
    "strokeCount": 10,
    "radical": "鬲",
    "meaningEn": "cauldron",
    "meaningKr": "솥 력",
    "meaningKrSource": "wiktionary",
    "level": "N1"
  },
  {
    "number": 194,
    "strokeCount": 10,
    "radical": "鬼",
    "meaningEn": "ghost",
    "meaningKr": "귀신 귀",
    "level": "N1",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 195,
    "strokeCount": 11,
    "radical": "魚",
    "meaningEn": "fish",
    "meaningKr": "물고기 어",
    "level": "N4",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 196,
    "strokeCount": 11,
    "radical": "鳥",
    "meaningEn": "bird",
    "meaningKr": "새 조",
    "level": "N4",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 197,
    "strokeCount": 11,
    "radical": "鹵",
    "meaningEn": "salt",
    "meaningKr": "소금 로",
    "meaningKrSource": "wiktionary",
    "level": "N1"
  },
  {
    "number": 198,
    "strokeCount": 11,
    "radical": "鹿",
    "meaningEn": "deer",
    "meaningKr": "사슴 록",
    "level": "N1",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 199,
    "strokeCount": 11,
    "radical": "麥",
    "meaningEn": "wheat",
    "meaningKr": "보리 맥",
    "meaningKrSource": "wiktionary",
    "level": "N2"
  },
  {
    "number": 200,
    "strokeCount": 11,
    "radical": "麻",
    "meaningEn": "hemp",
    "meaningKr": "삼 마",
    "level": "N1",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 201,
    "strokeCount": 12,
    "radical": "黃",
    "meaningEn": "yellow",
    "meaningKr": "누를 황",
    "meaningKrSource": "wiktionary",
    "level": "N2"
  },
  {
    "number": 202,
    "strokeCount": 12,
    "radical": "黍",
    "meaningEn": "millet",
    "meaningKr": "기장 서",
    "meaningKrSource": "wiktionary",
    "level": "N1"
  },
  {
    "number": 203,
    "strokeCount": 12,
    "radical": "黑",
    "meaningEn": "black",
    "meaningKr": "검을 흑",
    "meaningKrSource": "wiktionary",
    "level": "N4"
  },
  {
    "number": 204,
    "strokeCount": 12,
    "radical": "黹",
    "meaningEn": "embroidery",
    "meaningKr": "바느질할 치",
    "meaningKrSource": "wiktionary",
    "level": "N1"
  },
  {
    "number": 205,
    "strokeCount": 13,
    "radical": "黽",
    "meaningEn": "frog",
    "meaningKr": "힘쓸 민",
    "meaningKrSource": "wiktionary",
    "level": "N1"
  },
  {
    "number": 206,
    "strokeCount": 13,
    "radical": "鼎",
    "meaningEn": "tripod",
    "meaningKr": "솥 정",
    "meaningKrSource": "wiktionary",
    "level": "N1"
  },
  {
    "number": 207,
    "strokeCount": 13,
    "radical": "鼓",
    "meaningEn": "drum",
    "meaningKr": "북 고",
    "level": "N1",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 208,
    "strokeCount": 13,
    "radical": "鼠",
    "meaningEn": "rat",
    "meaningKr": "쥐 서",
    "meaningKrSource": "wiktionary",
    "level": "N1"
  },
  {
    "number": 209,
    "strokeCount": 14,
    "radical": "鼻",
    "meaningEn": "nose",
    "meaningKr": "코 비",
    "level": "N2",
    "meaningKrSource": "kanji-data"
  },
  {
    "number": 210,
    "strokeCount": 14,
    "radical": "齊",
    "meaningEn": "even",
    "meaningKr": "가지런할 제",
    "meaningKrSource": "wiktionary",
    "level": "N1"
  },
  {
    "number": 211,
    "strokeCount": 15,
    "radical": "齒",
    "meaningEn": "tooth",
    "meaningKr": "이 치",
    "meaningKrSource": "wiktionary",
    "level": "N2"
  },
  {
    "number": 212,
    "strokeCount": 16,
    "radical": "龍",
    "meaningEn": "dragon",
    "meaningKr": "용 룡",
    "meaningKrSource": "wiktionary",
    "level": "N1"
  },
  {
    "number": 213,
    "strokeCount": 16,
    "radical": "龜",
    "meaningEn": "turtle",
    "meaningKr": "거북 귀",
    "meaningKrSource": "wiktionary",
    "level": "N1"
  },
  {
    "number": 214,
    "strokeCount": 17,
    "radical": "龠",
    "meaningEn": "flute",
    "meaningKr": "피리 약",
    "meaningKrSource": "wiktionary",
    "level": "N1"
  }
]
