// Generated by scripts/build-study-data.mjs from data/study-*.json — do not edit by hand.
// Etymology text is model-authored (not cross-checked against a second
// source) and may be wrong for genuinely disputed characters — see
// data/raw/README.md. radicalNumber was cross-referenced against KanjiVG
// component data and, for ambiguous cases, japandict.com.

export interface StudyContent {
  kanjiId: string
  radicalNumber: number
  etymology: string
}

export const studyContentByKanjiId: Record<string, StudyContent> = {
  "N4-1": {
    "kanjiId": "N4-1",
    "radicalNumber": 9,
    "etymology": "회의자, 시루에 뚜껑을 덮어 합치는 모습에서 '모이다·합치다'는 뜻이 됨."
  },
  "N4-2": {
    "kanjiId": "N4-2",
    "radicalNumber": 30,
    "etymology": "회의자, 여러 것을 하나로 모아 덮은 모습에서 '같다'는 뜻이 됨."
  },
  "N4-3": {
    "kanjiId": "N4-3",
    "radicalNumber": 6,
    "etymology": "상형자, 손에 기록 도구를 든 모습을 본떠 '일, 사무'를 뜻하게 됨."
  },
  "N4-4": {
    "kanjiId": "N4-4",
    "radicalNumber": 132,
    "etymology": "상형자, 사람의 코 모양을 본뜬 글자. 자신을 가리킬 때 코를 가리키는 습관에서 '스스로'라는 뜻으로 쓰이게 됨."
  },
  "N4-5": {
    "kanjiId": "N4-5",
    "radicalNumber": 113,
    "etymology": "형성자, 제사 시(示)와 소리를 나타내는 土가 결합. 원래 토지신을 모시는 제단을 뜻하다가 '모임, 단체'로 뜻이 확장됨."
  },
  "N4-6": {
    "kanjiId": "N4-6",
    "radicalNumber": 105,
    "etymology": "회의자, 활(弓)을 쏘는 모습에서 '(화살이) 나가다, 피어나다'는 뜻이 됨."
  },
  "N4-7": {
    "kanjiId": "N4-7",
    "radicalNumber": 125,
    "etymology": "회의자, 본래 땔감을 모아 불을 피우는 모습에서 유래했다는 설이 있으며, 후에 사람·사물을 가리키는 말로 쓰이게 됨."
  },
  "N4-8": {
    "kanjiId": "N4-8",
    "radicalNumber": 32,
    "etymology": "형성자, 흙 토(土)와 소리를 나타내는 也가 결합해 '땅'을 뜻함."
  },
  "N4-9": {
    "kanjiId": "N4-9",
    "radicalNumber": 75,
    "etymology": "상형자, 원래 종을 걸어두는 받침대의 톱니 모양을 본뜬 글자였다가 '일, 업'의 뜻으로 쓰이게 됨."
  },
  "N4-10": {
    "kanjiId": "N4-10",
    "radicalNumber": 70,
    "etymology": "상형자, 두 척의 배를 나란히 묶은 모습(또는 쟁기의 모양)을 본떴다는 설이 있으며 '모나다, 방향'을 뜻하게 됨."
  },
  "N4-11": {
    "kanjiId": "N4-11",
    "radicalNumber": 69,
    "etymology": "회의자, 도끼(斤)로 나무(木)를 베어 땔감을 만드는 모습에서 유래했고, 후에 '새롭다'는 뜻으로 가차됨."
  },
  "N4-12": {
    "kanjiId": "N4-12",
    "radicalNumber": 32,
    "etymology": "형성자, 흙 토(土)와 소리를 나타내는 昜이 결합해 '마당, 장소'를 뜻함."
  },
  "N4-13": {
    "kanjiId": "N4-13",
    "radicalNumber": 30,
    "etymology": "회의자, 둥근 솥의 모습에서 '둥글다'는 뜻이었다가 사람 수를 세는 '인원'의 뜻으로 쓰이게 됨."
  },
  "N4-14": {
    "kanjiId": "N4-14",
    "radicalNumber": 117,
    "etymology": "상형자, 사람이 땅 위에 두 팔을 벌리고 서 있는 모습을 본뜸."
  },
  "N4-15": {
    "kanjiId": "N4-15",
    "radicalNumber": 169,
    "etymology": "회의자, 빗장이 걸린 문(門)을 두 손(廾)으로 여는 모습에서 '열다'는 뜻이 됨."
  },
  "N4-16": {
    "kanjiId": "N4-16",
    "radicalNumber": 64,
    "etymology": "상형자, 다섯 손가락을 편 손의 모양을 본뜸."
  },
  "N4-17": {
    "kanjiId": "N4-17",
    "radicalNumber": 19,
    "etymology": "상형자, 팔의 힘줄 또는 쟁기의 모양을 본떠 '힘'을 뜻하게 됨."
  },
  "N4-18": {
    "kanjiId": "N4-18",
    "radicalNumber": 30,
    "etymology": "형성자, 입 구(口)와 소리를 나타내는 門이 결합해 '묻다'를 뜻함."
  },
  "N4-19": {
    "kanjiId": "N4-19",
    "radicalNumber": 9,
    "etymology": "형성자, 사람 인(亻)과 소리를 나타내는 弋이 결합해 '대신하다, 세대'를 뜻함."
  },
  "N4-20": {
    "kanjiId": "N4-20",
    "radicalNumber": 72,
    "etymology": "회의자, 해(日)와 달(月)이 나란히 있는 모습에서 '밝다'는 뜻이 됨."
  },
  "N4-21": {
    "kanjiId": "N4-21",
    "radicalNumber": 19,
    "etymology": "형성자, 힘 력(力)과 소리를 나타내는 重이 결합해 '움직이다'를 뜻함."
  },
  "N4-22": {
    "kanjiId": "N4-22",
    "radicalNumber": 8,
    "etymology": "상형자, 높이 지은 큰 건물(누각)의 모양을 본떠 '높은 언덕, 수도'를 뜻하게 됨."
  },
  "N4-23": {
    "kanjiId": "N4-23",
    "radicalNumber": 109,
    "etymology": "상형자, 사람의 눈 모양을 본뜸."
  },
  "N4-24": {
    "kanjiId": "N4-24",
    "radicalNumber": 162,
    "etymology": "형성자, 뜻을 나타내는 辵(辶, 가다)와 소리를 나타내는 甬이 결합해 '통하다'를 뜻함."
  },
  "N4-25": {
    "kanjiId": "N4-25",
    "radicalNumber": 149,
    "etymology": "상형자, 혀에서 소리가 나오는 모습을 본떠 '말'을 뜻하게 됨."
  },
  "N4-26": {
    "kanjiId": "N4-26",
    "radicalNumber": 96,
    "etymology": "형성자, 구슬 옥(王/玉)과 소리를 나타내는 里가 결합. 원래 옥의 결을 다듬는다는 뜻에서 '이치, 다스리다'로 확장됨."
  },
  "N4-27": {
    "kanjiId": "N4-27",
    "radicalNumber": 9,
    "etymology": "회의자, 사람 인(亻)과 근본 본(本)이 결합해 '사람의 근본, 몸'을 뜻함."
  },
  "N4-28": {
    "kanjiId": "N4-28",
    "radicalNumber": 102,
    "etymology": "상형자, 경계로 나뉜 밭의 모양을 본뜸."
  },
  "N4-29": {
    "kanjiId": "N4-29",
    "radicalNumber": 3,
    "etymology": "상형자, 등잔의 심지에 불이 타는 모습을 본뜬 글자로, 중심이 되는 존재라는 뜻에서 '주인'을 뜻하게 됨."
  },
  "N4-30": {
    "kanjiId": "N4-30",
    "radicalNumber": 181,
    "etymology": "형성자, 머리 혈(頁)과 소리를 나타내는 是가 결합해 원래 '이마'를 뜻하다가 글의 앞머리인 '제목'을 뜻하게 됨."
  },
  "N4-31": {
    "kanjiId": "N4-31",
    "radicalNumber": 61,
    "etymology": "회의자, 소리 음(音)과 마음 심(心)이 결합해 마음속의 소리, 즉 '생각, 뜻'을 나타냄."
  },
  "N4-32": {
    "kanjiId": "N4-32",
    "radicalNumber": 1,
    "etymology": "상형자, 꽃받침(또는 새가 날아오르는 모습)을 본뜬 글자였다가 부정을 나타내는 말로 가차됨."
  },
  "N4-33": {
    "kanjiId": "N4-33",
    "radicalNumber": 9,
    "etymology": "형성자, 사람 인(亻)과 소리를 나타내는 乍가 결합해 '만들다, 짓다'를 뜻함."
  },
  "N4-34": {
    "kanjiId": "N4-34",
    "radicalNumber": 101,
    "etymology": "상형자, 나무 통이나 종의 모양을 본떴다는 설이 있으며 '쓰다, 사용하다'는 뜻으로 쓰이게 됨."
  },
  "N4-35": {
    "kanjiId": "N4-35",
    "radicalNumber": 53,
    "etymology": "회의자, 집 엄(广)과 손(又) 등이 결합해 손으로 길이를 재는 모습에서 '자, 법도, 정도'를 뜻하게 됨."
  },
  "N4-36": {
    "kanjiId": "N4-36",
    "radicalNumber": 57,
    "etymology": "형성자, 벌레 충(虫)과 소리를 나타내는 弘의 변형이 결합. 원래 딱딱한 껍질의 벌레를 가리키다가 '강하다'는 뜻으로 쓰이게 됨."
  },
  "N4-37": {
    "kanjiId": "N4-37",
    "radicalNumber": 12,
    "etymology": "회의자, 사사로움을 뜻하는 厶를 등지는(八) 모습에서 '공평하다, 공적인'이라는 뜻이 됨."
  },
  "N4-38": {
    "kanjiId": "N4-38",
    "radicalNumber": 64,
    "etymology": "형성자, 손 수(扌)와 소리를 나타내는 寺가 결합해 '손에 쥐다, 가지다'를 뜻함."
  },
  "N4-39": {
    "kanjiId": "N4-39",
    "radicalNumber": 166,
    "etymology": "형성자, 마을 리(里)와 소리를 나타내는 予가 결합해 '들판'을 뜻함."
  },
  "N4-40": {
    "kanjiId": "N4-40",
    "radicalNumber": 9,
    "etymology": "상형자, 원래 쟁기 등의 농기구 모양을 본뜬 글자였다가 '~으로써'라는 뜻으로 가차됨."
  },
  "N4-41": {
    "kanjiId": "N4-41",
    "radicalNumber": 61,
    "etymology": "회의자, 정수리(囟, 田으로 변형됨)와 마음 심(心)이 결합해 머리와 마음으로 '생각하다'는 뜻이 됨."
  },
  "N4-42": {
    "kanjiId": "N4-42",
    "radicalNumber": 40,
    "etymology": "회의자, 집(宀) 안에 돼지(豕)가 있는 모습으로, 옛날 집 아래에 가축을 기르던 데서 '집'을 뜻하게 됨."
  },
  "N4-43": {
    "kanjiId": "N4-43",
    "radicalNumber": 1,
    "etymology": "지사자, 十(열 십) 세 개를 이어 써서 '삼십 년', 즉 한 세대를 나타내다가 '세상, 시대'를 뜻하게 됨."
  },
  "N4-44": {
    "kanjiId": "N4-44",
    "radicalNumber": 36,
    "etymology": "회의자, 고기 육(肉/夕)을 두 개 겹쳐 써서 '많다'는 뜻을 나타냄."
  },
  "N4-45": {
    "kanjiId": "N4-45",
    "radicalNumber": 77,
    "etymology": "회의자, 목표(一)를 향해 발(止)이 똑바로 나아가는 모습에서 '바르다'는 뜻이 됨."
  },
  "N4-46": {
    "kanjiId": "N4-46",
    "radicalNumber": 40,
    "etymology": "회의자, 집(宀) 안에 여자(女)가 있는 모습에서 '편안하다'는 뜻이 됨."
  },
  "N4-47": {
    "kanjiId": "N4-47",
    "radicalNumber": 170,
    "etymology": "형성자, 언덕 부(阝)와 소리를 나타내는 完이 결합해 담으로 둘러싸인 큰 건물, 즉 '집, 관청'을 뜻함."
  },
  "N4-48": {
    "kanjiId": "N4-48",
    "radicalNumber": 61,
    "etymology": "상형자, 심장의 모양을 본떠 '마음'을 뜻하게 됨."
  },
  "N4-49": {
    "kanjiId": "N4-49",
    "radicalNumber": 102,
    "etymology": "형성자, 밭 전(田)과 소리를 나타내는 介가 결합해 밭과 밭 사이의 경계, 즉 '지경, 세계'를 뜻함."
  },
  "N4-50": {
    "kanjiId": "N4-50",
    "radicalNumber": 66,
    "etymology": "회의자, 회초리를 든 손(攵)이 아이(子)에게 본받을 것을 가르치는 모습에서 '가르치다'는 뜻이 됨."
  },
  "N4-51": {
    "kanjiId": "N4-51",
    "radicalNumber": 67,
    "etymology": "상형자, 몸에 새긴 문신(무늬)의 모양을 본떠 '무늬, 글'을 뜻하게 됨."
  },
  "N4-52": {
    "kanjiId": "N4-52",
    "radicalNumber": 10,
    "etymology": "지사자, 사람의 머리를 강조해 그린 모습에서 '으뜸, 처음'을 뜻하게 됨."
  },
  "N4-53": {
    "kanjiId": "N4-53",
    "radicalNumber": 166,
    "etymology": "회의자, 사람이 짐을 지고 있는 모습에서 '무겁다'는 뜻이 됨."
  },
  "N4-54": {
    "kanjiId": "N4-54",
    "radicalNumber": 162,
    "etymology": "형성자, 뜻을 나타내는 辵(辶)과 소리를 나타내는 斤이 결합해 '가깝다'를 뜻함."
  },
  "N4-55": {
    "kanjiId": "N4-55",
    "radicalNumber": 125,
    "etymology": "형성자, 늙을 로(耂)와 소리를 나타내는 丂가 결합. 원래 '나이 든 사람'을 뜻하다가 '깊이 생각하다'는 뜻으로 확장됨."
  },
  "N4-56": {
    "kanjiId": "N4-56",
    "radicalNumber": 102,
    "etymology": "회의자, 붓(聿)으로 밭의 경계(田)를 긋는 모습에서 '긋다, 그림'을 뜻하게 됨."
  },
  "N4-57": {
    "kanjiId": "N4-57",
    "radicalNumber": 85,
    "etymology": "형성자, 물 수(氵)와 소리를 나타내는 每가 결합해 '바다'를 뜻함."
  },
  "N4-58": {
    "kanjiId": "N4-58",
    "radicalNumber": 33,
    "etymology": "회의자, 선비 사(士)와 조개 패(貝)가 결합한 형태로, 물건을 내다 판다는 뜻을 나타냄."
  },
  "N4-59": {
    "kanjiId": "N4-59",
    "radicalNumber": 111,
    "etymology": "회의자, 화살(矢)이 과녁을 맞히듯 말(口)이 정확함을 나타내 '알다'는 뜻이 됨."
  },
  "N4-60": {
    "kanjiId": "N4-60",
    "radicalNumber": 162,
    "etymology": "회의자, 사람의 머리(首)를 나타내는 부분과 걷는 것을 뜻하는 辵(辶)이 결합해 '사람이 다니는 길'을 뜻함."
  },
  "N4-61": {
    "kanjiId": "N4-61",
    "radicalNumber": 172,
    "etymology": "회의자, 새(隹)가 나무(木) 위에 모여 앉은 모습에서 '모이다'는 뜻이 됨."
  },
  "N4-62": {
    "kanjiId": "N4-62",
    "radicalNumber": 18,
    "etymology": "회의자, 뼈를 발라내는 모습과 칼(刂)이 결합해 '나누다, 헤어지다'는 뜻이 됨."
  },
  "N4-63": {
    "kanjiId": "N4-63",
    "radicalNumber": 93,
    "etymology": "형성자, 소 우(牛)와 소리를 나타내는 勿이 결합. 원래 다양한 색의 소를 가리키다가 '사물, 물건'을 뜻하게 됨."
  },
  "N4-64": {
    "kanjiId": "N4-64",
    "radicalNumber": 9,
    "etymology": "회의자, 사람 인(亻)과 관리(吏)가 결합해 명을 받아 일을 시키는 모습에서 '부리다, 시키다'는 뜻이 됨."
  },
  "N4-65": {
    "kanjiId": "N4-65",
    "radicalNumber": 30,
    "etymology": "회의자, 입 구(口)를 세 개 겹쳐 써서 여러 사람 또는 여러 물건을 나타내다가 '물건, 등급'을 뜻하게 됨."
  },
  "N4-66": {
    "kanjiId": "N4-66",
    "radicalNumber": 149,
    "etymology": "회의자, 말씀 언(言)과 열 십(十)이 결합해 수를 세어 말한다는 데서 '세다, 계산하다'는 뜻이 됨."
  },
  "N4-67": {
    "kanjiId": "N4-67",
    "radicalNumber": 78,
    "etymology": "회의자, 부서진 뼈(歹)와 사람(匕)이 결합해 사람이 죽어 뼈만 남은 모습에서 '죽다'는 뜻이 됨."
  },
  "N4-68": {
    "kanjiId": "N4-68",
    "radicalNumber": 93,
    "etymology": "형성자, 소 우(牛)와 소리를 나타내는 寺가 결합. 원래 수소 한 마리를 가리키다가 '특별하다'는 뜻으로 확장됨."
  },
  "N4-69": {
    "kanjiId": "N4-69",
    "radicalNumber": 115,
    "etymology": "형성자, 벼 화(禾)와 소리를 나타내는 厶가 결합해 개인이 거두는 곡식, 즉 '사사롭다'는 뜻이 됨."
  },
  "N4-70": {
    "kanjiId": "N4-70",
    "radicalNumber": 38,
    "etymology": "형성자, 여자 여(女)와 소리를 나타내는 台가 결합해 '시작하다'를 뜻함."
  },
  "N4-71": {
    "kanjiId": "N4-71",
    "radicalNumber": 74,
    "etymology": "회의자, 풀숲(艹) 사이로 해(日)가 떠오르고 아직 달(月)이 남아있는 새벽 모습에서 '아침'을 뜻하게 됨."
  },
  "N4-72": {
    "kanjiId": "N4-72",
    "radicalNumber": 162,
    "etymology": "형성자, 뜻을 나타내는 辵(辶)과 소리를 나타내는 軍이 결합해 '옮기다, 운반하다'는 뜻이 됨."
  },
  "N4-73": {
    "kanjiId": "N4-73",
    "radicalNumber": 120,
    "etymology": "형성자, 실 사(糸)와 소리를 나타내는 冬이 결합. 원래 실을 다 감은 끝부분을 뜻하다가 '마치다'는 뜻이 됨."
  },
  "N4-74": {
    "kanjiId": "N4-74",
    "radicalNumber": 30,
    "etymology": "회의자, 사사로울 사(厶)와 입 구(口)가 결합한 글자로, 원래 '기쁘다'는 뜻이었다가 '돈대, 무대' 등의 뜻으로 쓰이게 됨."
  },
  "N4-75": {
    "kanjiId": "N4-75",
    "radicalNumber": 53,
    "etymology": "형성자, 집 엄(广)과 소리를 나타내는 요소가 결합해 '넓다'는 뜻을 나타냄."
  },
  "N4-76": {
    "kanjiId": "N4-76",
    "radicalNumber": 9,
    "etymology": "형성자, 사람 인(亻)과 소리를 나타내는 主가 결합해 '살다, 머무르다'는 뜻이 됨."
  },
  "N4-77": {
    "kanjiId": "N4-77",
    "radicalNumber": 109,
    "etymology": "회의자, 숟가락으로 그릇에 물건을 가득 채운 모습에서 '가득 차다, 참되다'는 뜻이 됨."
  },
  "N4-78": {
    "kanjiId": "N4-78",
    "radicalNumber": 74,
    "etymology": "회의자, 손(又)에 고기(肉)를 쥔 모습에서 '가지다, 있다'는 뜻이 됨."
  },
  "N4-79": {
    "kanjiId": "N4-79",
    "radicalNumber": 30,
    "etymology": "상형자, 사람의 입 모양을 본뜸."
  },
  "N4-80": {
    "kanjiId": "N4-80",
    "radicalNumber": 42,
    "etymology": "지사자, 작은 점 몇 개로 양이 적음을 나타냄."
  },
  "N4-81": {
    "kanjiId": "N4-81",
    "radicalNumber": 102,
    "etymology": "형성자, 밭 전(田)과 소리를 나타내는 丁이 결합해 밭 사이의 두둑, 즉 구획된 땅을 뜻하다가 '마을, 동네'의 뜻으로도 쓰이게 됨."
  },
  "N4-82": {
    "kanjiId": "N4-82",
    "radicalNumber": 68,
    "etymology": "회의자, 쌀 미(米)와 말 두(斗)가 결합해 곡식을 되로 헤아리는 모습에서 '헤아리다, 재료, 요금'을 뜻하게 됨."
  },
  "N4-83": {
    "kanjiId": "N4-83",
    "radicalNumber": 48,
    "etymology": "상형자, 물건을 만들 때 쓰는 도구(자, 곱자)의 모양을 본떠 '장인, 만들다'는 뜻이 됨."
  },
  "N4-84": {
    "kanjiId": "N4-84",
    "radicalNumber": 54,
    "etymology": "회의자, 붓 율(聿)과 길게 걷는 모습(廴)이 결합해 법도를 세워 나간다는 데서 '세우다'는 뜻이 됨."
  },
  "N4-85": {
    "kanjiId": "N4-85",
    "radicalNumber": 116,
    "etymology": "형성자, 구멍 혈(穴)과 소리를 나타내는 工이 결합해 '비다, 하늘'을 뜻함."
  },
  "N4-86": {
    "kanjiId": "N4-86",
    "radicalNumber": 61,
    "etymology": "형성자, 마음 심(心)과 소리를 나타내는 及이 결합해 급히 붙잡으려는 마음에서 '급하다'는 뜻이 됨."
  },
  "N4-87": {
    "kanjiId": "N4-87",
    "radicalNumber": 77,
    "etymology": "상형자, 발자국의 모양을 본뜬 글자로, 원래 '발'을 뜻하다가 걸음을 멈춘다는 데서 '그치다'는 뜻이 됨."
  },
  "N4-88": {
    "kanjiId": "N4-88",
    "radicalNumber": 162,
    "etymology": "형성자, 뜻을 나타내는 辵(辶)과 두 손으로 물건을 받쳐 든 모습이 결합해 '보내다, 배웅하다'는 뜻이 됨."
  },
  "N4-89": {
    "kanjiId": "N4-89",
    "radicalNumber": 18,
    "etymology": "형성자, 칼 도(刀/刂)와 소리를 나타내는 七이 결합해 '끊다, 자르다'는 뜻이 됨."
  },
  "N4-90": {
    "kanjiId": "N4-90",
    "radicalNumber": 159,
    "etymology": "형성자, 수레 거(車)와 소리를 나타내는 專이 결합해 '구르다, 회전하다'는 뜻이 됨."
  },
  "N4-91": {
    "kanjiId": "N4-91",
    "radicalNumber": 112,
    "etymology": "형성자, 돌 석(石)과 소리를 나타내는 幵이 결합해 '갈다, 연마하다'는 뜻이 됨."
  },
  "N4-92": {
    "kanjiId": "N4-92",
    "radicalNumber": 157,
    "etymology": "상형자, 무릎에서 발끝까지의 다리 모양을 본떠 '발'을 뜻하게 됨."
  },
  "N4-93": {
    "kanjiId": "N4-93",
    "radicalNumber": 116,
    "etymology": "형성자, 구멍 혈(穴)과 소리를 나타내는 九가 결합해 구멍 속까지 파고든다는 데서 '깊이 연구하다'는 뜻이 됨."
  },
  "N4-94": {
    "kanjiId": "N4-94",
    "radicalNumber": 75,
    "etymology": "상형자, 나무(木) 받침 위에 방울이나 현악기가 달린 모습을 본뜬 글자로 원래 '악기, 음악'을 뜻하다가 '즐겁다'는 뜻으로 확장됨."
  },
  "N4-95": {
    "kanjiId": "N4-95",
    "radicalNumber": 156,
    "etymology": "형성자, 달릴 주(走)와 소리를 나타내는 己가 결합해 '일어나다, 시작하다'는 뜻이 됨."
  },
  "N4-96": {
    "kanjiId": "N4-96",
    "radicalNumber": 109,
    "etymology": "회의자, 양(羊)과 눈 목(目)이 결합한 형태로 원래 눈에 잘 띈다는 뜻이었다가 '붙다, 입다, 도착하다'는 뜻으로 쓰이게 됨."
  },
  "N4-97": {
    "kanjiId": "N4-97",
    "radicalNumber": 53,
    "etymology": "형성자, 집 엄(广)과 소리를 나타내는 占이 결합해 물건을 벌여 놓고 파는 곳, 즉 '가게'를 뜻함."
  },
  "N4-98": {
    "kanjiId": "N4-98",
    "radicalNumber": 104,
    "etymology": "형성자, 병들 녁(疒)과 소리를 나타내는 丙이 결합해 '병들다'를 뜻함."
  },
  "N4-99": {
    "kanjiId": "N4-99",
    "radicalNumber": 154,
    "etymology": "형성자, 조개 패(貝)와 도끼 근(斤) 두 개가 결합. 원래 저당·담보를 뜻하다가 '본바탕, 성질'의 뜻으로 확장됨."
  },
  "N4-100": {
    "kanjiId": "N4-100",
    "radicalNumber": 60,
    "etymology": "형성자, 조금 걸을 척(彳)과 소리를 나타내는 寺가 결합해 '기다리다'는 뜻이 됨."
  },
  "N5-1": {
    "kanjiId": "N5-1",
    "radicalNumber": 72,
    "etymology": "상형자, 해의 둥근 모양을 본뜬 글자."
  },
  "N5-2": {
    "kanjiId": "N5-2",
    "radicalNumber": 1,
    "etymology": "지사자, 가로줄 하나로 '하나'라는 수를 나타냄."
  },
  "N5-3": {
    "kanjiId": "N5-3",
    "radicalNumber": 31,
    "etymology": "회의자, 나라의 영토를 나타내는 에운담(囗) 안에 옥을 지닌 임금(王)이 있음을 나타냄."
  },
  "N5-4": {
    "kanjiId": "N5-4",
    "radicalNumber": 9,
    "etymology": "상형자, 옆에서 본 사람이 서 있는 모습을 본뜸."
  },
  "N5-5": {
    "kanjiId": "N5-5",
    "radicalNumber": 51,
    "etymology": "원래 사람이 벼(禾)를 지고 가는 모습에서 온 회의자로, 한 해 농사의 수확을 나타내다가 '해'라는 뜻이 됨."
  },
  "N5-6": {
    "kanjiId": "N5-6",
    "radicalNumber": 37,
    "etymology": "상형자, 양팔과 양다리를 벌리고 서 있는 사람의 모습으로 '크다'를 나타냄."
  },
  "N5-7": {
    "kanjiId": "N5-7",
    "radicalNumber": 24,
    "etymology": "지사자, 원래 세로줄 하나로 매듭을 나타내다가 '열'을 뜻하게 됨."
  },
  "N5-8": {
    "kanjiId": "N5-8",
    "radicalNumber": 7,
    "etymology": "지사자, 가로줄 두 개로 '둘'을 나타냄."
  },
  "N5-9": {
    "kanjiId": "N5-9",
    "radicalNumber": 75,
    "etymology": "지사자, 나무(木) 뿌리 부분에 점을 찍어 '뿌리·근본'을 나타냄."
  },
  "N5-10": {
    "kanjiId": "N5-10",
    "radicalNumber": 2,
    "etymology": "지사자, 어떤 물건(囗)의 한가운데를 세로줄로 꿰뚫어 '가운데'를 나타냄."
  },
  "N5-11": {
    "kanjiId": "N5-11",
    "radicalNumber": 168,
    "etymology": "상형자, 머리카락이 긴 노인이 지팡이를 짚은 모습에서 '길다'는 뜻이 됨."
  },
  "N5-12": {
    "kanjiId": "N5-12",
    "radicalNumber": 17,
    "etymology": "회의자, 발(止)이 경계(凵) 밖으로 나가는 모습을 나타냄 (초목이 땅 위로 돋아나는 모습이라는 설도 있음)."
  },
  "N5-13": {
    "kanjiId": "N5-13",
    "radicalNumber": 1,
    "etymology": "지사자, 가로줄 세 개로 '셋'을 나타냄."
  },
  "N5-14": {
    "kanjiId": "N5-14",
    "radicalNumber": 72,
    "etymology": "형성자, 뜻을 나타내는 日과 소리를 나타내는 寺가 합쳐짐."
  },
  "N5-15": {
    "kanjiId": "N5-15",
    "radicalNumber": 144,
    "etymology": "상형자, 사거리(십자로)의 모습을 본떠 '가다·다니다'는 뜻이 됨."
  },
  "N5-16": {
    "kanjiId": "N5-16",
    "radicalNumber": 147,
    "etymology": "회의자, 사람(儿) 위에 눈(目)을 강조해 그려 '보다'는 뜻을 나타냄."
  },
  "N5-17": {
    "kanjiId": "N5-17",
    "radicalNumber": 74,
    "etymology": "상형자, 초승달의 모양을 본뜸."
  },
  "N5-18": {
    "kanjiId": "N5-18",
    "radicalNumber": 18,
    "etymology": "회의자, 칼(刀)로 물건을 나누는 모습(八)을 그려 '나누다'는 뜻을 나타냄."
  },
  "N5-19": {
    "kanjiId": "N5-19",
    "radicalNumber": 60,
    "etymology": "회의자, 걸을 척(彳)과 발이 실에 묶여 뒤처짐(幺+夂)을 나타내 '뒤'를 뜻함."
  },
  "N5-20": {
    "kanjiId": "N5-20",
    "radicalNumber": 18,
    "etymology": "원래 배(舟)가 발(止)과 함께 나아가는 모습이었다가, 자형이 바뀌며 칼(刀→刂)이 더해진 것으로 '앞'을 뜻하게 됨."
  },
  "N5-21": {
    "kanjiId": "N5-21",
    "radicalNumber": 100,
    "etymology": "상형자, 땅 위로 풀(屮)이 돋아나는 모습을 본떠 '나다·살다'는 뜻이 됨."
  },
  "N5-22": {
    "kanjiId": "N5-22",
    "radicalNumber": 7,
    "etymology": "지사자, 하늘과 땅(二) 사이에서 무언가 교차하는 모습(×)으로 '다섯'을 나타냄."
  },
  "N5-23": {
    "kanjiId": "N5-23",
    "radicalNumber": 169,
    "etymology": "회의자, 문(門) 틈 사이로 해(日)가 비치는 모습에서 '사이'를 뜻함 (원래는 달 月이었다가 日로 바뀜)."
  },
  "N5-24": {
    "kanjiId": "N5-24",
    "radicalNumber": 1,
    "etymology": "지사자, 기준선 위에 점(짧은 획)을 찍어 '위'를 나타냄."
  },
  "N5-25": {
    "kanjiId": "N5-25",
    "radicalNumber": 75,
    "etymology": "전통적으로 나무(木) 사이로 해(日)가 떠오르는 모습이라 설명되나, 갑골문 자형을 근거로 양끝을 묶은 자루 모양이라는 해석도 있음."
  },
  "N5-26": {
    "kanjiId": "N5-26",
    "radicalNumber": 31,
    "etymology": "지사자, 원래는 가로줄 네 개였다가 코에서 숨이 갈라져 나가는 모습(囗+八)을 본뜬 자형으로 바뀌어 '넷'을 나타냄."
  },
  "N5-27": {
    "kanjiId": "N5-27",
    "radicalNumber": 9,
    "etymology": "회의자, 사람(人)이 무언가를 머금은(一) 모습에서 '바로 지금'이라는 뜻이 됨."
  },
  "N5-28": {
    "kanjiId": "N5-28",
    "radicalNumber": 167,
    "etymology": "형성자, 흙(土) 속에 파묻힌 쇳덩이와 소리를 나타내는 부분이 합쳐져 '쇠·금'을 뜻함."
  },
  "N5-29": {
    "kanjiId": "N5-29",
    "radicalNumber": 5,
    "etymology": "지사자, 팔을 구부린 모습을 본떠 '아홉'이라는 수를 나타냄 (자형의 유래는 명확히 밝혀지지 않음)."
  },
  "N5-30": {
    "kanjiId": "N5-30",
    "radicalNumber": 11,
    "etymology": "상형자, 뾰족한 물건이 안으로 들어가는 모습을 본뜸."
  },
  "N5-31": {
    "kanjiId": "N5-31",
    "radicalNumber": 39,
    "etymology": "회의자, 아이(子)가 두 손으로 지붕(冖) 아래에서 배우는 모습(원자형 學)을 간략화함."
  },
  "N5-32": {
    "kanjiId": "N5-32",
    "radicalNumber": 189,
    "etymology": "상형자, 높이 지은 누각·망루의 모습을 본뜸."
  },
  "N5-33": {
    "kanjiId": "N5-33",
    "radicalNumber": 13,
    "etymology": "圓의 약자로, 에운담(囗→冂) 안에 둥근 도구가 있어 '둥글다'는 뜻이었다가 일본에서 화폐 단위로도 쓰임."
  },
  "N5-34": {
    "kanjiId": "N5-34",
    "radicalNumber": 39,
    "etymology": "상형자, 강보에 싸인 아기의 모습을 본뜸."
  },
  "N5-35": {
    "kanjiId": "N5-35",
    "radicalNumber": 36,
    "etymology": "회의자, 저녁(夕)에 거북 껍질로 점(卜)을 치던 관습에서, 원래 점치던 때가 아닌 때를 가리켜 '바깥'을 뜻하게 됨."
  },
  "N5-36": {
    "kanjiId": "N5-36",
    "radicalNumber": 12,
    "etymology": "지사자, 두 갈래로 나뉜 모습을 본떠 '여덟'을 나타냄."
  },
  "N5-37": {
    "kanjiId": "N5-37",
    "radicalNumber": 12,
    "etymology": "자형의 유래가 명확하지 않으며, 가차되어 '여섯'이라는 수를 나타냄."
  },
  "N5-38": {
    "kanjiId": "N5-38",
    "radicalNumber": 1,
    "etymology": "지사자, 기준선 아래에 점(짧은 획)을 찍어 '아래'를 나타냄."
  },
  "N5-39": {
    "kanjiId": "N5-39",
    "radicalNumber": 9,
    "etymology": "원래 익은 보리 이삭의 모습을 본뜬 상형자였는데, 소리가 같아 '오다'라는 뜻으로 가차되어 쓰이게 됨."
  },
  "N5-40": {
    "kanjiId": "N5-40",
    "radicalNumber": 84,
    "etymology": "氣의 약자로, 원래 피어오르는 수증기·구름의 모습을 본뜬 상형자에서 비롯됨."
  },
  "N5-41": {
    "kanjiId": "N5-41",
    "radicalNumber": 42,
    "etymology": "상형자, 작은 점(모래알) 세 개를 그려 '작다'는 뜻을 나타냄."
  },
  "N5-42": {
    "kanjiId": "N5-42",
    "radicalNumber": 1,
    "etymology": "원래 무언가를 자르는 모습에서 비롯됐으며 가차되어 '일곱'이라는 수를 나타냄."
  },
  "N5-43": {
    "kanjiId": "N5-43",
    "radicalNumber": 46,
    "etymology": "상형자, 봉우리가 솟은 산의 모습을 본뜸."
  },
  "N5-44": {
    "kanjiId": "N5-44",
    "radicalNumber": 149,
    "etymology": "형성자, 뜻을 나타내는 言과 소리를 나타내는 舌이 합쳐짐."
  },
  "N5-45": {
    "kanjiId": "N5-45",
    "radicalNumber": 38,
    "etymology": "상형자, 두 손을 모으고 무릎을 꿇은 여성의 모습을 본뜸."
  },
  "N5-46": {
    "kanjiId": "N5-46",
    "radicalNumber": 21,
    "etymology": "회의자, 두 사람이 서로 등을 지고 있는 모습(背의 원자)에서, 집이 남쪽을 향할 때 등지는 방향인 '북쪽'을 뜻하게 됨."
  },
  "N5-47": {
    "kanjiId": "N5-47",
    "radicalNumber": 24,
    "etymology": "원래 절굿공이 모양을 본뜬 상형자였는데, 가차되어 십이지의 일곱째(말)와 정오를 뜻하게 됨."
  },
  "N5-48": {
    "kanjiId": "N5-48",
    "radicalNumber": 106,
    "etymology": "一과 白(소리를 나타냄)이 합쳐진 형성자로 '백'을 나타냄."
  },
  "N5-49": {
    "kanjiId": "N5-49",
    "radicalNumber": 72,
    "etymology": "회의자, 붓(聿)으로 말한 것을 적는다는 데서 '쓰다'는 뜻이 됨."
  },
  "N5-50": {
    "kanjiId": "N5-50",
    "radicalNumber": 10,
    "etymology": "회의자, 사람(儿) 위에 발을 그려 남보다 앞서 나아감을 나타냄."
  },
  "N5-51": {
    "kanjiId": "N5-51",
    "radicalNumber": 30,
    "etymology": "회의자, 저녁(夕) 어두울 때 자기 이름을 입(口)으로 말해 알린다는 데서 '이름'을 뜻함."
  },
  "N5-52": {
    "kanjiId": "N5-52",
    "radicalNumber": 47,
    "etymology": "상형자, 물이 굽이쳐 흐르는 하천의 모습을 본뜸."
  },
  "N5-53": {
    "kanjiId": "N5-53",
    "radicalNumber": 24,
    "etymology": "지사자, 사람 인(人)에 가로줄을 더해 '천'이라는 수를 나타냄."
  },
  "N5-54": {
    "kanjiId": "N5-54",
    "radicalNumber": 85,
    "etymology": "상형자, 물이 흐르는 모습을 본뜸."
  },
  "N5-55": {
    "kanjiId": "N5-55",
    "radicalNumber": 24,
    "etymology": "회의자, 소(牛)를 반으로 나눈다(八)는 데서 '반쪽'을 뜻함."
  },
  "N5-56": {
    "kanjiId": "N5-56",
    "radicalNumber": 102,
    "etymology": "회의자, 밭(田)에서 힘(力)을 쓰는 사람이라는 데서 '사내'를 뜻함."
  },
  "N5-57": {
    "kanjiId": "N5-57",
    "radicalNumber": 146,
    "etymology": "상형자, 해가 질 때 새가 둥지에 깃드는 모습을 본떠 '서쪽'을 나타냄."
  },
  "N5-58": {
    "kanjiId": "N5-58",
    "radicalNumber": 173,
    "etymology": "형성자, 비(雨)와 번개가 치는 모습이 합쳐져 원래 '번개'를 뜻하다가 '전기'라는 뜻으로도 쓰임."
  },
  "N5-59": {
    "kanjiId": "N5-59",
    "radicalNumber": 75,
    "etymology": "형성자, 나무(木)와 소리를 나타내는 交가 합쳐짐 (원래 나무로 만든 울타리·형틀을 뜻하다가 '학교'로 쓰이게 됨)."
  },
  "N5-60": {
    "kanjiId": "N5-60",
    "radicalNumber": 149,
    "etymology": "형성자, 뜻을 나타내는 言과 소리를 나타내는 吾가 합쳐져 '말씀'을 뜻함."
  },
  "N5-61": {
    "kanjiId": "N5-61",
    "radicalNumber": 32,
    "etymology": "상형자, 땅 위에 흙무더기가 쌓인 모습을 본뜸."
  },
  "N5-62": {
    "kanjiId": "N5-62",
    "radicalNumber": 75,
    "etymology": "상형자, 뿌리·줄기·가지가 있는 나무의 모습을 본뜸."
  },
  "N5-63": {
    "kanjiId": "N5-63",
    "radicalNumber": 128,
    "etymology": "형성자, 뜻을 나타내는 耳와 소리를 나타내는 門이 합쳐져 '듣다'는 뜻이 됨."
  },
  "N5-64": {
    "kanjiId": "N5-64",
    "radicalNumber": 184,
    "etymology": "회의자, 밥그릇에 뚜껑을 덮은 모습을 본떠 '밥·먹다'는 뜻이 됨."
  },
  "N5-65": {
    "kanjiId": "N5-65",
    "radicalNumber": 159,
    "etymology": "상형자, 위에서 내려다본 수레바퀴와 굴대의 모습을 본뜸."
  },
  "N5-66": {
    "kanjiId": "N5-66",
    "radicalNumber": 9,
    "etymology": "원래 사람(人/亻)이 짐을 짊어진 모습(荷의 원자)이었다가, 가차되어 '무엇'이라는 뜻으로 쓰이게 됨."
  },
  "N5-67": {
    "kanjiId": "N5-67",
    "radicalNumber": 51,
    "etymology": "원래 악기(종·북 종류)의 모습을 본뜬 상형자였는데 가차되어 '남쪽'을 뜻하게 됨."
  },
  "N5-68": {
    "kanjiId": "N5-68",
    "radicalNumber": 1,
    "etymology": "萬의 약자로, 원래 전갈의 모습을 본뜬 상형자였다가 가차되어 '만'이라는 수를 나타냄."
  },
  "N5-69": {
    "kanjiId": "N5-69",
    "radicalNumber": 80,
    "etymology": "每의 약자로, 비녀를 꽂아 머리를 꾸민 여자(母 계열)의 모습에서 '매양·마다'라는 뜻으로 쓰이게 됨."
  },
  "N5-70": {
    "kanjiId": "N5-70",
    "radicalNumber": 106,
    "etymology": "상형자, 엄지손톱 또는 촛불의 흰 빛 등을 본떴다는 여러 설이 있으며 '희다'는 뜻을 나타냄."
  },
  "N5-71": {
    "kanjiId": "N5-71",
    "radicalNumber": 37,
    "etymology": "지사자, 사람(大)의 머리 위(一)를 가리켜 '하늘'을 나타냄."
  },
  "N5-72": {
    "kanjiId": "N5-72",
    "radicalNumber": 80,
    "etymology": "상형자, 두 손을 모은 여자(女)의 모습에 젖가슴을 나타내는 두 점을 더해 '어머니'를 나타냄."
  },
  "N5-73": {
    "kanjiId": "N5-73",
    "radicalNumber": 86,
    "etymology": "상형자, 타오르는 불꽃의 모습을 본뜸."
  },
  "N5-74": {
    "kanjiId": "N5-74",
    "radicalNumber": 30,
    "etymology": "회의자, 손(又)과 입(口)을 그려, 오른손으로 밥을 먹으며 남을 돕는다는 데서 '오른쪽·돕다'는 뜻이 됨."
  },
  "N5-75": {
    "kanjiId": "N5-75",
    "radicalNumber": 149,
    "etymology": "형성자, 뜻을 나타내는 言과 소리를 나타내는 売가 합쳐짐."
  },
  "N5-76": {
    "kanjiId": "N5-76",
    "radicalNumber": 29,
    "etymology": "회의자, 손(又) 두 개를 나란히 그려 서로 손을 맞잡고 돕는 사이인 '벗'을 나타냄."
  },
  "N5-77": {
    "kanjiId": "N5-77",
    "radicalNumber": 48,
    "etymology": "회의자, 왼손(손의 변형)과 도구를 뜻하는 工을 그려, 왼손으로 일을 돕는다는 데서 '왼쪽'을 나타냄."
  },
  "N5-78": {
    "kanjiId": "N5-78",
    "radicalNumber": 9,
    "etymology": "회의자, 사람(人/亻)이 나무(木) 그늘 아래에서 쉬는 모습을 본뜸."
  },
  "N5-79": {
    "kanjiId": "N5-79",
    "radicalNumber": 88,
    "etymology": "상형자, 손에 도끼·회초리 같은 도구를 쥔 모습을 본떠 집안을 다스리는 '아버지'를 나타냄."
  },
  "N5-80": {
    "kanjiId": "N5-80",
    "radicalNumber": 173,
    "etymology": "상형자, 하늘(一)에서 빗방울이 떨어지는 모습을 본뜸."
  }
}
