// Generated by scripts/build-study-data.mjs from data/study-*.json — do not edit by hand.
// Etymology text is model-authored (not cross-checked against a second
// source) and may be wrong for genuinely disputed characters — see
// data/raw/README.md. radicalNumber was cross-referenced against KanjiVG
// component data and, for ambiguous cases, japandict.com.

export interface StudyContent {
  kanjiId: string
  radicalNumber: number
  etymology: string
}

export const studyContentByKanjiId: Record<string, StudyContent> = {
  "N3-1": {
    "kanjiId": "N3-1",
    "radicalNumber": 66,
    "etymology": "형성자, 칠 복(攵)과 소리를 나타내는 正이 결합해 바르게 다스린다는 데서 '정사'를 뜻함."
  },
  "N3-2": {
    "kanjiId": "N3-2",
    "radicalNumber": 149,
    "etymology": "형성자, 말씀 언(言)과 소리를 나타내는 義가 결합해 '의논하다'는 뜻이 됨."
  },
  "N3-3": {
    "kanjiId": "N3-3",
    "radicalNumber": 83,
    "etymology": "상형자, 원래 눈을 찔린 노예의 모습을 본떴다는 설이 있으며 후에 '백성'을 뜻하게 됨."
  },
  "N3-4": {
    "kanjiId": "N3-4",
    "radicalNumber": 162,
    "etymology": "회의자, 뜻을 나타내는 辵(辶)과 수레 거(車)가 결합해 수레가 줄지어 이어지는 모습에서 '잇닿다'는 뜻이 됨."
  },
  "N3-5": {
    "kanjiId": "N3-5",
    "radicalNumber": 41,
    "etymology": "회의자, 마디 촌(寸)과 소리 나는 부분이 결합해 마주 대한다는 뜻을 나타냄."
  },
  "N3-6": {
    "kanjiId": "N3-6",
    "radicalNumber": 163,
    "etymology": "형성자, 고을 읍(阝)과 소리를 나타내는 咅가 결합해 '나누다, 부서, 거느리다'는 뜻이 됨."
  },
  "N3-7": {
    "kanjiId": "N3-7",
    "radicalNumber": 30,
    "etymology": "회의자, 그릇에 뚜껑을 덮어 합치는 모습에서 '합하다'는 뜻이 됨."
  },
  "N3-8": {
    "kanjiId": "N3-8",
    "radicalNumber": 50,
    "etymology": "형성자, 수건 건(巾)과 소리를 나타내는 요소가 결합해 사람이 모여 물건을 사고파는 '저자, 시장'을 뜻함."
  },
  "N3-9": {
    "kanjiId": "N3-9",
    "radicalNumber": 13,
    "etymology": "회의자, 덮을 멱(冂)과 들 입(入)이 결합해 안으로 들어간다는 데서 '안'을 뜻함."
  },
  "N3-10": {
    "kanjiId": "N3-10",
    "radicalNumber": 109,
    "etymology": "회의자, 나무 목(木)과 눈 목(目)이 결합해 나무를 눈으로 살펴본다는 데서 '보다, 서로'를 뜻하게 됨."
  },
  "N3-11": {
    "kanjiId": "N3-11",
    "radicalNumber": 40,
    "etymology": "형성자, 집 면(宀)과 소리를 나타내는 疋이 결합해 집안이 안정된다는 데서 '정하다'는 뜻이 됨."
  },
  "N3-12": {
    "kanjiId": "N3-12",
    "radicalNumber": 31,
    "etymology": "상형자, 물이 소용돌이치는 모양을 본떠 '돌다'는 뜻이 됨."
  },
  "N3-13": {
    "kanjiId": "N3-13",
    "radicalNumber": 162,
    "etymology": "형성자, 뜻을 나타내는 辵(辶)과 소리를 나타내는 巽이 결합해 '가려 뽑다'는 뜻이 됨."
  },
  "N3-14": {
    "kanjiId": "N3-14",
    "radicalNumber": 119,
    "etymology": "상형자, 낟알이 흩어져 있는 벼의 모습을 본떠 '쌀'을 뜻하게 됨."
  },
  "N3-15": {
    "kanjiId": "N3-15",
    "radicalNumber": 40,
    "etymology": "회의자, 집(宀) 안에 재물이 가득 찬 모습에서 '차다, 열매, 실제'를 뜻하게 됨."
  },
  "N3-16": {
    "kanjiId": "N3-16",
    "radicalNumber": 169,
    "etymology": "형성자, 문 문(門)과 소리를 나타내는 关이 결합해 문의 빗장, 즉 '관문, 관계하다'는 뜻이 됨."
  },
  "N3-17": {
    "kanjiId": "N3-17",
    "radicalNumber": 85,
    "etymology": "형성자, 물 수(氵)와 소리를 나타내는 夬이 결합. 원래 물길을 튼다는 뜻에서 '결단하다'는 뜻으로 확장됨."
  },
  "N3-18": {
    "kanjiId": "N3-18",
    "radicalNumber": 11,
    "etymology": "회의자, 들 입(入)과 구슬 옥(玉)이 결합해 흠 없는 완전한 옥, 즉 '온전하다'는 뜻이 됨."
  },
  "N3-19": {
    "kanjiId": "N3-19",
    "radicalNumber": 145,
    "etymology": "회의자, 털 모(毛)와 옷 의(衣)가 결합해 털이 겉으로 드러난 옷, 즉 '겉'을 뜻하게 됨."
  },
  "N3-20": {
    "kanjiId": "N3-20",
    "radicalNumber": 62,
    "etymology": "형성자, 창 과(戈)와 소리를 나타내는 単이 결합해 '싸우다'는 뜻이 됨."
  },
  "N3-21": {
    "kanjiId": "N3-21",
    "radicalNumber": 120,
    "etymology": "형성자, 실 사(糸)와 소리를 나타내는 巠이 결합. 원래 베틀의 날실을 뜻하다가 '지나다, 다스리다, 경서'로 확장됨."
  },
  "N3-22": {
    "kanjiId": "N3-22",
    "radicalNumber": 73,
    "etymology": "회의자, 무릅쓸 모의 변형과 취할 취(取)가 결합해 위험을 무릅쓰고 빼앗는다는 데서 '가장'이라는 뜻으로 가차됨."
  },
  "N3-23": {
    "kanjiId": "N3-23",
    "radicalNumber": 96,
    "etymology": "형성자, 구슬 옥(王/玉)과 소리를 나타내는 見이 결합. 원래 옥의 광채를 뜻하다가 '나타나다'는 뜻으로 확장됨."
  },
  "N3-24": {
    "kanjiId": "N3-24",
    "radicalNumber": 149,
    "etymology": "형성자, 말씀 언(言)과 소리를 나타내는 周가 결합해 말이 두루 고르다는 데서 '고르다, 조사하다'는 뜻이 됨."
  },
  "N3-25": {
    "kanjiId": "N3-25",
    "radicalNumber": 21,
    "etymology": "회의자, 서 있는 사람(亻)과 거꾸로 선 사람(匕)이 결합해 사람이 변화하는 모습에서 '되다, 변하다'는 뜻이 됨."
  },
  "N3-26": {
    "kanjiId": "N3-26",
    "radicalNumber": 58,
    "etymology": "형성자, 밭 전(田)과 소리를 나타내는 요소가 결합해 밭의 넓이가 가치와 맞먹는다는 데서 '마땅하다, 당하다'는 뜻이 됨."
  },
  "N3-27": {
    "kanjiId": "N3-27",
    "radicalNumber": 120,
    "etymology": "형성자, 실 사(糸)와 소리를 나타내는 勺이 결합. 실로 묶는다는 데서 '맺다, 약속하다'는 뜻이 됨."
  },
  "N3-28": {
    "kanjiId": "N3-28",
    "radicalNumber": 185,
    "etymology": "상형자, 머리카락과 눈이 있는 머리 모양을 본뜸."
  },
  "N3-29": {
    "kanjiId": "N3-29",
    "radicalNumber": 85,
    "etymology": "회의자, 물 수(氵)와 갈 거(去)가 결합. 물처럼 공평한 기준이라는 데서 '법'을 뜻하게 됨."
  },
  "N3-30": {
    "kanjiId": "N3-30",
    "radicalNumber": 61,
    "etymology": "형성자, 마음 심(忄)과 소리를 나타내는 生이 결합해 타고난 마음, 즉 '성품'을 뜻함."
  },
  "N3-31": {
    "kanjiId": "N3-31",
    "radicalNumber": 146,
    "etymology": "상형자, 사람이 허리에 손을 얹은 모습을 본떠 원래 '허리'를 뜻하다가 몸의 중심이라는 데서 '요긴하다, 구하다'로 확장됨."
  },
  "N3-32": {
    "kanjiId": "N3-32",
    "radicalNumber": 18,
    "etymology": "회의자, 칼 도(刂)로 나뭇가지를 가지런히 자르는 모습에서 '자르다, 절제하다, 만들다'는 뜻이 됨."
  },
  "N3-33": {
    "kanjiId": "N3-33",
    "radicalNumber": 85,
    "etymology": "형성자, 물 수(氵)와 소리를 나타내는 台가 결합. 원래 물길을 다스린다는 뜻에서 '다스리다'로 확장됨."
  },
  "N3-34": {
    "kanjiId": "N3-34",
    "radicalNumber": 19,
    "etymology": "형성자, 힘 력(力)과 소리를 나타내는 敄가 결합해 '힘쓰다'는 뜻이 됨."
  },
  "N3-35": {
    "kanjiId": "N3-35",
    "radicalNumber": 62,
    "etymology": "형성자, 창 과(戈)와 소리를 나타내는 丁이 결합. 원래 무기를 완성한다는 데서 '이루다'는 뜻이 됨."
  },
  "N3-36": {
    "kanjiId": "N3-36",
    "radicalNumber": 74,
    "etymology": "형성자, 달 월(月)과 소리를 나타내는 其가 결합해 달이 차고 기우는 주기, 즉 '기간, 기약하다'는 뜻이 됨."
  },
  "N3-37": {
    "kanjiId": "N3-37",
    "radicalNumber": 29,
    "etymology": "회의자, 귀 이(耳)와 손 우(又)가 결합해 옛날 전쟁에서 적의 귀를 잘라 취하던 데서 '가지다, 취하다'는 뜻이 됨."
  },
  "N3-38": {
    "kanjiId": "N3-38",
    "radicalNumber": 163,
    "etymology": "형성자, 고을 읍(阝)과 소리를 나타내는 者가 결합해 사람이 많이 모인 큰 고을, 즉 '도읍'을 뜻함."
  },
  "N3-39": {
    "kanjiId": "N3-39",
    "radicalNumber": 30,
    "etymology": "회의자, 벼 화(禾)와 입 구(口)가 결합. 곡식을 고루 나눠 먹는다는 데서 '화목하다'는 뜻이 됨."
  },
  "N3-40": {
    "kanjiId": "N3-40",
    "radicalNumber": 75,
    "etymology": "형성자, 나무 목(木)과 소리를 나타내는 幾가 결합해 나무로 만든 베틀, 즉 '틀, 기계'를 뜻함."
  },
  "N3-41": {
    "kanjiId": "N3-41",
    "radicalNumber": 51,
    "etymology": "상형자, 물 위에 떠 있는 부평초 또는 저울대가 평평한 모습을 본떠 '평평하다'는 뜻이 됨."
  },
  "N3-42": {
    "kanjiId": "N3-42",
    "radicalNumber": 19,
    "etymology": "회의자, 힘 력(力)과 입 구(口)가 결합해 말로 힘을 보태 격려한다는 데서 '더하다'는 뜻이 됨."
  },
  "N3-43": {
    "kanjiId": "N3-43",
    "radicalNumber": 29,
    "etymology": "회의자, 배 모양의 변형을 사이에 두고 손과 손이 주고받는 모습에서 '받다'는 뜻이 됨."
  },
  "N3-44": {
    "kanjiId": "N3-44",
    "radicalNumber": 120,
    "etymology": "형성자, 실 사(糸)와 소리를 나타내는 요소가 결합해 실을 이어간다는 데서 '잇다, 계속하다'는 뜻이 됨."
  },
  "N3-45": {
    "kanjiId": "N3-45",
    "radicalNumber": 162,
    "etymology": "회의자, 뜻을 나타내는 辵(辶)과 새 추(隹)가 결합해 새가 앞으로만 나아가듯 '나아가다'는 뜻이 됨."
  },
  "N3-46": {
    "kanjiId": "N3-46",
    "radicalNumber": 66,
    "etymology": "형성자, 칠 복(攵)과 소리를 나타내는 婁가 결합해 헤아려 센다는 데서 '셈, 수'를 뜻함."
  },
  "N3-47": {
    "kanjiId": "N3-47",
    "radicalNumber": 149,
    "etymology": "형성자, 말씀 언(言)과 소리를 나타내는 己가 결합해 '기록하다'는 뜻이 됨."
  },
  "N3-48": {
    "kanjiId": "N3-48",
    "radicalNumber": 18,
    "etymology": "회의자, 옷 의(衤)와 칼 도(刀)가 결합해 옷을 만들 때 가장 먼저 옷감을 자른다는 데서 '처음'을 뜻하게 됨."
  },
  "N3-49": {
    "kanjiId": "N3-49",
    "radicalNumber": 64,
    "etymology": "형성자, 손 수(扌)와 소리를 나타내는 旨가 결합해 '손가락, 가리키다'는 뜻이 됨."
  },
  "N3-50": {
    "kanjiId": "N3-50",
    "radicalNumber": 75,
    "etymology": "형성자, 나무 목(木)과 소리를 나타내는 요소가 결합. 원래 저울추를 뜻하다가 저울질하는 힘, 즉 '권세'를 뜻하게 됨."
  },
  "N3-51": {
    "kanjiId": "N3-51",
    "radicalNumber": 65,
    "etymology": "회의자, 대나무 가지 모양과 손(又)이 결합한 모습에서 '가지, 지탱하다'는 뜻이 됨."
  },
  "N3-52": {
    "kanjiId": "N3-52",
    "radicalNumber": 100,
    "etymology": "형성자, 날 생(生)과 소리를 나타내는 요소가 결합해 '낳다'는 뜻이 됨."
  },
  "N3-53": {
    "kanjiId": "N3-53",
    "radicalNumber": 86,
    "etymology": "형성자, 검을 흑(黑)과 소리를 나타내는 占이 결합해 작은 얼룩, 즉 '점'을 뜻함."
  },
  "N3-54": {
    "kanjiId": "N3-54",
    "radicalNumber": 32,
    "etymology": "회의자, 죄인을 뜻하는 부분과 손으로 다스리는 모습이 결합해 죄를 갚는다는 데서 '갚다, 알리다'는 뜻이 됨."
  },
  "N3-55": {
    "kanjiId": "N3-55",
    "radicalNumber": 85,
    "etymology": "형성자, 물 수(氵)와 소리를 나타내는 요소가 결합해 물을 건넌다는 데서 '건너다, 이루다, 다하다'는 뜻이 됨."
  },
  "N3-56": {
    "kanjiId": "N3-56",
    "radicalNumber": 85,
    "etymology": "형성자, 물 수(氵)와 소리를 나타내는 舌이 결합. 원래 물이 흐르는 소리를 나타내다가 '살다, 활발하다'는 뜻으로 확장됨."
  },
  "N3-57": {
    "kanjiId": "N3-57",
    "radicalNumber": 27,
    "etymology": "회의자, 언덕(厂) 아래에서 샘물(泉)이 솟아나는 모습에서 '근원, 들판'을 뜻하게 됨."
  },
  "N3-58": {
    "kanjiId": "N3-58",
    "radicalNumber": 12,
    "etymology": "회의자, 두 손으로 물건을 함께 받쳐 든 모습에서 '함께'라는 뜻이 됨."
  },
  "N3-59": {
    "kanjiId": "N3-59",
    "radicalNumber": 60,
    "etymology": "회의자, 조금 걸을 척(彳)과 손으로 재물(貝)을 쥔 모습이 결합해 길에서 재물을 얻는다는 데서 '얻다'는 뜻이 됨."
  },
  "N3-60": {
    "kanjiId": "N3-60",
    "radicalNumber": 148,
    "etymology": "회의자, 칼 도(刀)로 소(牛)의 뿔(角)을 발라내는 모습에서 '가르다, 풀다'는 뜻이 됨."
  },
  "N3-61": {
    "kanjiId": "N3-61",
    "radicalNumber": 8,
    "etymology": "상형자, 사람이 다리를 꼬고 있는 모습을 본떠 '교차하다, 사귀다'는 뜻이 됨."
  },
  "N3-62": {
    "kanjiId": "N3-62",
    "radicalNumber": 154,
    "etymology": "형성자, 조개 패(貝)와 소리를 나타내는 次가 결합해 '재물, 밑천'을 뜻함."
  },
  "N3-63": {
    "kanjiId": "N3-63",
    "radicalNumber": 6,
    "etymology": "상형자, 베틀의 북 모양을 본떴다는 설이 있으며 '주다, 나'라는 뜻으로 가차되었고, 나중에 '미리'라는 뜻으로도 쓰임."
  },
  "N3-64": {
    "kanjiId": "N3-64",
    "radicalNumber": 30,
    "etymology": "회의자, 집(宀)에 창문(口)이 나 있는 모습에서 창이 향한 방향, 즉 '향하다'는 뜻이 됨."
  },
  "N3-65": {
    "kanjiId": "N3-65",
    "radicalNumber": 170,
    "etymology": "형성자, 언덕 부(阝)와 소리를 나타내는 祭가 결합. 원래 담이 만나는 경계를 뜻하다가 '즈음, 사이, 국제'로 확장됨."
  },
  "N3-66": {
    "kanjiId": "N3-66",
    "radicalNumber": 19,
    "etymology": "형성자, 힘 력(力)과 소리를 나타내는 朕이 결합해 '이기다, 뛰어나다'는 뜻이 됨."
  },
  "N3-67": {
    "kanjiId": "N3-67",
    "radicalNumber": 176,
    "etymology": "상형자, 사람의 얼굴 윤곽과 눈을 강조해 그린 모양을 본떠 '낯, 얼굴'을 뜻하게 됨."
  },
  "N3-68": {
    "kanjiId": "N3-68",
    "radicalNumber": 30,
    "etymology": "회의자, 소 우(牛)와 입 구(口)가 결합해 소를 제물로 바치며 신에게 아뢰는 모습에서 '고하다'는 뜻이 됨."
  },
  "N3-69": {
    "kanjiId": "N3-69",
    "radicalNumber": 29,
    "etymology": "회의자, 언덕(厂)을 손(又)으로 밀어 뒤집는 모습에서 '뒤집다, 반대하다'는 뜻이 됨."
  },
  "N3-70": {
    "kanjiId": "N3-70",
    "radicalNumber": 18,
    "etymology": "형성자, 칼 도(刂)와 소리를 나타내는 半이 결합해 반으로 갈라 나눈다는 데서 '판단하다'는 뜻이 됨."
  },
  "N3-71": {
    "kanjiId": "N3-71",
    "radicalNumber": 149,
    "etymology": "형성자, 말씀 언(言)과 소리를 나타내는 忍이 결합해 '알다, 인정하다'는 뜻이 됨."
  },
  "N3-72": {
    "kanjiId": "N3-72",
    "radicalNumber": 28,
    "etymology": "회의자, 사람 머리 위 별빛 모양과 터럭 삼(彡)이 결합한 글자로, 원래 별자리 이름이었다가 '참여하다, 뵈다'는 뜻으로 가차됨."
  },
  "N3-73": {
    "kanjiId": "N3-73",
    "radicalNumber": 18,
    "etymology": "회의자, 벼 화(禾)와 칼 도(刂)가 결합해 벼를 잘 베어 이롭다는 데서 '이롭다'는 뜻이 됨."
  },
  "N3-74": {
    "kanjiId": "N3-74",
    "radicalNumber": 120,
    "etymology": "형성자, 실 사(糸)와 소리를 나타내는 且가 결합해 실을 엮는다는 데서 '짜다, 조직'을 뜻함."
  },
  "N3-75": {
    "kanjiId": "N3-75",
    "radicalNumber": 9,
    "etymology": "회의자, 사람 인(亻)과 말씀 언(言)이 결합해 사람의 말은 믿을 수 있어야 한다는 데서 '믿다'는 뜻이 됨."
  },
  "N3-76": {
    "kanjiId": "N3-76",
    "radicalNumber": 32,
    "etymology": "형성자, 흙 토(土)와 소리를 나타내는 才가 결합해 '있다'는 뜻이 됨."
  },
  "N3-77": {
    "kanjiId": "N3-77",
    "radicalNumber": 9,
    "etymology": "회의자, 사람 인(亻)과 소 우(牛)가 결합해 소를 잡아 부위별로 나누듯 일을 나눈다는 데서 '가지, 사건'을 뜻하게 됨."
  },
  "N3-78": {
    "kanjiId": "N3-78",
    "radicalNumber": 9,
    "etymology": "형성자, 사람 인(亻)과 소리를 나타내는 則이 결합해 '곁'을 뜻함."
  },
  "N3-79": {
    "kanjiId": "N3-79",
    "radicalNumber": 9,
    "etymology": "형성자, 사람 인(亻)과 소리를 나타내는 壬이 결합해 '맡기다'는 뜻이 됨."
  },
  "N3-80": {
    "kanjiId": "N3-80",
    "radicalNumber": 57,
    "etymology": "회의자, 활 궁(弓)에 시위를 매어 당기는 모습에서 '끌다, 당기다'는 뜻이 됨."
  },
  "N3-81": {
    "kanjiId": "N3-81",
    "radicalNumber": 85,
    "etymology": "상형자, 원래 짐승 가죽으로 만든 옷의 모양을 본떴다가 '구하다'는 뜻으로 가차됨."
  },
  "N3-82": {
    "kanjiId": "N3-82",
    "radicalNumber": 63,
    "etymology": "형성자, 지게 호(戶)와 소리를 나타내는 斤이 결합해 원래 도끼로 나무 베는 소리를 나타내다가 '장소, ~하는 바'로 뜻이 확장됨."
  },
  "N3-83": {
    "kanjiId": "N3-83",
    "radicalNumber": 76,
    "etymology": "회의자, 하품 흠(欠)과 얼음 빙(冫)이 결합해 재채기하는 모습을 본떴다는 설이 있으며 '다음, 버금'을 뜻하게 됨."
  },
  "N3-84": {
    "kanjiId": "N3-84",
    "radicalNumber": 72,
    "etymology": "형성자, 해 일(日)과 소리를 나타내는 乍가 결합해 '어제, 지난'을 뜻함."
  },
  "N3-85": {
    "kanjiId": "N3-85",
    "radicalNumber": 149,
    "etymology": "형성자, 말씀 언(言)과 소리를 나타내는 侖이 결합해 '논하다'는 뜻이 됨."
  },
  "N3-86": {
    "kanjiId": "N3-86",
    "radicalNumber": 40,
    "etymology": "회의자, 집 면(宀)과 언덕의 변형이 결합해 관청 건물을 나타내다가 그곳에서 일하는 '벼슬아치'를 뜻하게 됨."
  },
  "N3-87": {
    "kanjiId": "N3-87",
    "radicalNumber": 32,
    "etymology": "형성자, 흙 토(土)와 소리를 나타내는 曽이 결합해 흙을 겹겹이 쌓는다는 데서 '더하다, 늘다'는 뜻이 됨."
  },
  "N3-88": {
    "kanjiId": "N3-88",
    "radicalNumber": 9,
    "etymology": "회의자, 사람 인(亻)과 실 사(系)가 결합해 사람을 실로 맨다는 데서 '매다, 관계되다'는 뜻이 됨."
  },
  "N3-89": {
    "kanjiId": "N3-89",
    "radicalNumber": 61,
    "etymology": "형성자, 마음 심(心)과 소리를 나타내는 咸이 결합해 '느끼다'는 뜻이 됨."
  },
  "N3-90": {
    "kanjiId": "N3-90",
    "radicalNumber": 61,
    "etymology": "형성자, 마음 심(忄)과 소리를 나타내는 靑이 결합해 마음에서 우러나는 '정, 감정'을 뜻함."
  },
  "N3-91": {
    "kanjiId": "N3-91",
    "radicalNumber": 64,
    "etymology": "회의자, 손 수(扌)와 창 수(殳)가 결합해 손으로 무언가를 내던지는 모습에서 '던지다'는 뜻이 됨."
  },
  "N3-92": {
    "kanjiId": "N3-92",
    "radicalNumber": 113,
    "etymology": "상형자, 신에게 제사 지내는 제단의 모양을 본떠 신의 뜻을 사람에게 '보이다'는 뜻이 됨."
  },
  "N3-93": {
    "kanjiId": "N3-93",
    "radicalNumber": 34,
    "etymology": "형성자, 뜻을 나타내는 부분과 칠 복(夂)이 결합해 '변하다'는 뜻이 됨."
  },
  "N3-94": {
    "kanjiId": "N3-94",
    "radicalNumber": 64,
    "etymology": "형성자, 손 수(扌)와 소리를 나타내는 丁이 결합해 '치다'는 뜻이 됨."
  },
  "N3-95": {
    "kanjiId": "N3-95",
    "radicalNumber": 109,
    "etymology": "회의자, 눈 목(目) 위에 숨을 은(乚) 등을 더해 숨은 것도 똑바로 살펴본다는 데서 '곧다'는 뜻이 됨."
  },
  "N3-96": {
    "kanjiId": "N3-96",
    "radicalNumber": 1,
    "etymology": "상형자, 저울의 양쪽 접시가 나란히 달린 모습을 본떠 '두, 짝'을 뜻하게 됨."
  },
  "N3-97": {
    "kanjiId": "N3-97",
    "radicalNumber": 56,
    "etymology": "형성자, 장인 공(工)과 소리를 나타내는 弋이 결합해 '법, 의식'을 뜻함."
  },
  "N3-98": {
    "kanjiId": "N3-98",
    "radicalNumber": 112,
    "etymology": "형성자, 돌 석(石)과 소리를 나타내는 隺이 결합해 돌처럼 '굳다, 확실하다'는 뜻이 됨."
  },
  "N3-99": {
    "kanjiId": "N3-99",
    "radicalNumber": 75,
    "etymology": "상형자, 나무(木) 위에 열매가 열린 모습을 본떠 '열매, 결과'를 뜻하게 됨."
  },
  "N3-100": {
    "kanjiId": "N3-100",
    "radicalNumber": 40,
    "etymology": "형성자, 집 면(宀)과 골 곡(谷)이 결합해 집이 물건을 담아내듯 사람이 받아들인다는 데서 '용납하다, 얼굴 모습'을 뜻하게 됨."
  },
  "N3-101": {
    "kanjiId": "N3-101",
    "radicalNumber": 61,
    "etymology": "지사자, 나무 말뚝(弋)에 끈을 단단히 묶은 모습에서 '반드시'라는 뜻이 됨."
  },
  "N3-102": {
    "kanjiId": "N3-102",
    "radicalNumber": 85,
    "etymology": "형성자, 물 수(氵)와 소리를 나타내는 寅이 결합해 물이 길게 흘러간다는 데서 '펴다, 넓히다, 연출하다'는 뜻이 됨."
  },
  "N3-103": {
    "kanjiId": "N3-103",
    "radicalNumber": 77,
    "etymology": "형성자, 그칠 지(止)와 소리를 나타내는 요소가 결합. 원래 목성의 운행 주기를 뜻하다가 '해, 나이'를 뜻하게 됨."
  },
  "N3-104": {
    "kanjiId": "N3-104",
    "radicalNumber": 6,
    "etymology": "회의자, 손과 손이 물건을 서로 잡아당기는 모습에서 '다투다'는 뜻이 됨."
  },
  "N3-105": {
    "kanjiId": "N3-105",
    "radicalNumber": 149,
    "etymology": "형성자, 말씀 언(言)과 소리를 나타내는 炎이 결합해 '말씀, 이야기하다'는 뜻이 됨."
  },
  "N3-106": {
    "kanjiId": "N3-106",
    "radicalNumber": 130,
    "etymology": "상형자, 원래 곰의 모양을 본뜬 글자였다가 곰의 재주가 뛰어나다는 데서 '능하다'는 뜻으로 가차됨."
  },
  "N3-107": {
    "kanjiId": "N3-107",
    "radicalNumber": 9,
    "etymology": "회의자, 사람 인(亻)과 설 립(立)이 결합해 사람이 서 있는 곳, 즉 '자리'를 뜻하게 됨."
  },
  "N3-108": {
    "kanjiId": "N3-108",
    "radicalNumber": 122,
    "etymology": "회의자, 그물 망(罒)과 곧을 직(直)이 결합. 원래 죄인을 놓아준다는 뜻에서 '두다, 놓다'는 뜻으로 확장됨."
  },
  "N3-109": {
    "kanjiId": "N3-109",
    "radicalNumber": 85,
    "etymology": "회의자, 물 수(氵)와 아이가 거꾸로 떠내려가는 모습이 결합해 '흐르다'는 뜻이 됨."
  },
  "N3-110": {
    "kanjiId": "N3-110",
    "radicalNumber": 75,
    "etymology": "형성자, 나무 목(木)과 소리를 나타내는 各이 결합. 원래 나뭇가지가 뻗은 모양에서 '격식, 바로잡다'로 확장됨."
  },
  "N3-111": {
    "kanjiId": "N3-111",
    "radicalNumber": 103,
    "etymology": "회의자, 사람이 지팡이를 짚고 길에서 망설이는 모습에서 '의심하다'는 뜻이 됨."
  },
  "N3-112": {
    "kanjiId": "N3-112",
    "radicalNumber": 162,
    "etymology": "형성자, 뜻을 나타내는 辵(辶)과 소리를 나타내는 咼가 결합해 '지나다, 지나치다'는 뜻이 됨."
  },
  "N3-113": {
    "kanjiId": "N3-113",
    "radicalNumber": 44,
    "etymology": "회의자, 자 척(尺)과 입 구(口)가 결합한 글자로, 원래 몸을 굽힌다는 뜻에서 '판, 관청, 상황'으로 확장됨."
  },
  "N3-114": {
    "kanjiId": "N3-114",
    "radicalNumber": 66,
    "etymology": "형성자, 칠 복(攵)과 소리를 나타내는 方이 결합해 쳐서 내쫓는다는 데서 '놓다, 놓아주다'는 뜻이 됨."
  },
  "N3-115": {
    "kanjiId": "N3-115",
    "radicalNumber": 50,
    "etymology": "형성자, 수건 건(巾)과 소리를 나타내는 尚이 결합. 원래 긴 치마를 뜻하다가 '늘 그러하다, 항상'으로 확장됨."
  },
  "N3-116": {
    "kanjiId": "N3-116",
    "radicalNumber": 94,
    "etymology": "형성자, 개 견(犬)과 소리를 나타내는 나뭇조각 모양이 결합해 '모양, 형상, 문서'를 뜻함."
  },
  "N3-117": {
    "kanjiId": "N3-117",
    "radicalNumber": 96,
    "etymology": "형성자, 구슬 옥(王/玉)과 소리를 나타내는 求가 결합해 '둥근 옥, 공'을 뜻함."
  },
  "N3-118": {
    "kanjiId": "N3-118",
    "radicalNumber": 128,
    "etymology": "형성자, 귀 이(耳)와 소리를 나타내는 戠이 결합. 원래 귀담아듣고 기록한다는 뜻에서 '직분, 일'로 확장됨."
  },
  "N3-119": {
    "kanjiId": "N3-119",
    "radicalNumber": 1,
    "etymology": "상형자, 두 손으로 물건을 서로 주고받는 모습을 본떠 '주다'는 뜻이 됨."
  },
  "N3-120": {
    "kanjiId": "N3-120",
    "radicalNumber": 9,
    "etymology": "형성자, 사람 인(亻)과 소리를 나타내는 共이 결합해 '이바지하다, 바치다'는 뜻이 됨."
  },
  "N3-121": {
    "kanjiId": "N3-121",
    "radicalNumber": 60,
    "etymology": "회의자, 조금 걸을 척(彳)과 창 수(殳)가 결합해 변방을 순찰하며 지키는 모습에서 '부역, 부리다'는 뜻이 됨."
  },
  "N3-122": {
    "kanjiId": "N3-122",
    "radicalNumber": 75,
    "etymology": "형성자, 나무 목(木)과 소리를 나타내는 冓가 결합해 나무를 엮어 짓는다는 데서 '얽다, 짜다'는 뜻이 됨."
  },
  "N3-123": {
    "kanjiId": "N3-123",
    "radicalNumber": 18,
    "etymology": "형성자, 칼 도(刂)와 소리를 나타내는 害가 결합해 '베다, 나누다'는 뜻이 됨."
  },
  "N3-124": {
    "kanjiId": "N3-124",
    "radicalNumber": 154,
    "etymology": "형성자, 조개 패(貝)와 소리를 나타내는 弗이 결합해 재물을 흩어 쓴다는 데서 '쓰다, 소비하다'는 뜻이 됨."
  },
  "N3-125": {
    "kanjiId": "N3-125",
    "radicalNumber": 9,
    "etymology": "회의자, 사람 인(亻)과 손 촌(寸)이 결합해 사람에게 손으로 물건을 건네는 모습에서 '주다, 붙이다'는 뜻이 됨."
  },
  "N3-126": {
    "kanjiId": "N3-126",
    "radicalNumber": 102,
    "etymology": "상형자, 나무 가지에 열매가 달린 모양(또는 등잔 기름 접시)을 본떴다는 설이 있으며 '말미암다, ~로부터'를 뜻하게 됨."
  },
  "N3-127": {
    "kanjiId": "N3-127",
    "radicalNumber": 149,
    "etymology": "형성자, 말씀 언(言)과 소리를 나타내는 兌가 결합해 '말씀, 설명하다, 달래다'는 뜻이 됨."
  },
  "N3-128": {
    "kanjiId": "N3-128",
    "radicalNumber": 172,
    "etymology": "형성자, 새 추(隹)와 소리를 나타내는 堇이 결합해 '어렵다'는 뜻이 됨."
  },
  "N3-129": {
    "kanjiId": "N3-129",
    "radicalNumber": 9,
    "etymology": "형성자, 사람 인(亻)과 소리를 나타내는 憂가 결합. 원래 근심하듯 조심스러운 모습에서 '넉넉하다, 부드럽다, 뛰어나다'로 확장됨."
  },
  "N3-130": {
    "kanjiId": "N3-130",
    "radicalNumber": 37,
    "etymology": "상형자, 사람(大)의 머리에 비녀를 꽂은 모습을 본떠 성인 남자, 즉 '지아비'를 뜻하게 됨."
  },
  "N3-131": {
    "kanjiId": "N3-131",
    "radicalNumber": 29,
    "etymology": "형성자, 얽힐 구(丩)와 칠 복(攵)이 결합해 죄인을 잡아들인다는 데서 '거두다'는 뜻이 됨."
  },
  "N3-132": {
    "kanjiId": "N3-132",
    "radicalNumber": 69,
    "etymology": "회의자, 실타래를 도끼(斤)로 끊는 모습에서 '끊다, 결단하다'는 뜻이 됨."
  },
  "N3-133": {
    "kanjiId": "N3-133",
    "radicalNumber": 112,
    "etymology": "상형자, 벼랑 아래 놓인 돌의 모양을 본뜸."
  },
  "N3-134": {
    "kanjiId": "N3-134",
    "radicalNumber": 162,
    "etymology": "형성자, 뜻을 나타내는 辵(辶)과 소리를 나타내는 韋가 결합해 '어긋나다, 다르다'는 뜻이 됨."
  },
  "N3-135": {
    "kanjiId": "N3-135",
    "radicalNumber": 85,
    "etymology": "형성자, 물 수(氵)와 소리를 나타내는 肖가 결합해 물이 점점 줄어든다는 데서 '사라지다, 없애다'는 뜻이 됨."
  },
  "N3-136": {
    "kanjiId": "N3-136",
    "radicalNumber": 113,
    "etymology": "형성자, 보일 시(示)와 소리를 나타내는 申이 결합해 하늘에 제사 지내는 대상, 즉 '신, 귀신'을 뜻함."
  },
  "N3-137": {
    "kanjiId": "N3-137",
    "radicalNumber": 102,
    "etymology": "회의자, 짐승의 발자국 모양과 밭 전(田)이 결합. 원래 짐승 발자국을 뜻하다가 순서대로 놓인 모습에서 '차례'로 확장됨."
  },
  "N3-138": {
    "kanjiId": "N3-138",
    "radicalNumber": 147,
    "etymology": "회의자, 지아비 부(夫)와 볼 견(見)이 결합해 어른이 살펴서 정한 법도, 즉 '법, 규칙'을 뜻하게 됨."
  },
  "N3-139": {
    "kanjiId": "N3-139",
    "radicalNumber": 144,
    "etymology": "형성자, 다닐 행(行)과 소리를 나타내는 术이 결합해 사람이 다니는 방법, 즉 '재주, 기술'을 뜻함."
  },
  "N3-140": {
    "kanjiId": "N3-140",
    "radicalNumber": 9,
    "etymology": "회의자, 사람 인(亻)과 화살통을 갖춘 모습이 결합해 미리 갖춘다는 데서 '갖추다, 대비하다'는 뜻이 됨."
  },
  "N3-141": {
    "kanjiId": "N3-141",
    "radicalNumber": 40,
    "etymology": "형성자, 집 면(宀)과 소리를 나타내는 乇이 결합해 '집'을 뜻함."
  },
  "N3-142": {
    "kanjiId": "N3-142",
    "radicalNumber": 40,
    "etymology": "회의자, 집(宀) 안에서 말(言)이 어그러져 다툼이 생기는 모습에서 '해치다'는 뜻이 됨."
  },
  "N3-143": {
    "kanjiId": "N3-143",
    "radicalNumber": 164,
    "etymology": "회의자, 술 유(酉)와 몸을 굽힌 사람(己)이 결합해 술을 나누어 따르는 모습에서 '나누다, 짝짓다'는 뜻이 됨."
  },
  "N3-144": {
    "kanjiId": "N3-144",
    "radicalNumber": 149,
    "etymology": "형성자, 말씀 언(言)과 소리를 나타내는 敬이 결합해 말로 조심하도록 일깨운다는 데서 '경계하다'는 뜻이 됨."
  },
  "N3-145": {
    "kanjiId": "N3-145",
    "radicalNumber": 130,
    "etymology": "회의자, 자식 자(子)를 거꾸로 그린 모양과 고기 육(肉)이 결합해 아이를 낳아 기르는 모습에서 '기르다'는 뜻이 됨."
  },
  "N3-146": {
    "kanjiId": "N3-146",
    "radicalNumber": 50,
    "etymology": "형성자, 수건 건(巾)과 소리를 나타내는 庶의 변형이 결합해 자리에 까는 돗자리, 즉 '자리'를 뜻함."
  },
  "N3-147": {
    "kanjiId": "N3-147",
    "radicalNumber": 149,
    "etymology": "형성자, 말씀 언(言)과 소리를 나타내는 方이 결합해 말로 두루 물어 찾는다는 데서 '찾다, 방문하다'는 뜻이 됨."
  },
  "N3-148": {
    "kanjiId": "N3-148",
    "radicalNumber": 4,
    "etymology": "회의자, 나무 위에 사람이 다리를 벌리고 올라탄 모습에서 '타다'는 뜻이 됨."
  },
  "N3-149": {
    "kanjiId": "N3-149",
    "radicalNumber": 78,
    "etymology": "형성자, 부서진 뼈(歹)와 소리를 나타내는 戔이 결합해 '남다, 해치다'는 뜻이 됨."
  },
  "N3-150": {
    "kanjiId": "N3-150",
    "radicalNumber": 61,
    "etymology": "형성자, 마음 심(心)과 소리를 나타내는 相이 결합해 '생각하다'는 뜻이 됨."
  },
  "N3-151": {
    "kanjiId": "N3-151",
    "radicalNumber": 33,
    "etymology": "상형자, 악기를 치는 모습을 본떠 '소리'를 뜻하게 됨."
  },
  "N3-152": {
    "kanjiId": "N3-152",
    "radicalNumber": 61,
    "etymology": "형성자, 마음 심(心)과 소리를 나타내는 今이 결합해 지금 마음에 두고 있다는 데서 '생각하다'는 뜻이 됨."
  },
  "N3-153": {
    "kanjiId": "N3-153",
    "radicalNumber": 19,
    "etymology": "형성자, 힘 력(力)과 소리를 나타내는 且가 결합해 '돕다'는 뜻이 됨."
  },
  "N3-154": {
    "kanjiId": "N3-154",
    "radicalNumber": 19,
    "etymology": "회의자, 불(火)과 힘 력(力)이 결합해 불을 밝히며 힘써 일한다는 데서 '일하다, 수고롭다'는 뜻이 됨."
  },
  "N3-155": {
    "kanjiId": "N3-155",
    "radicalNumber": 9,
    "etymology": "형성자, 사람 인(亻)과 소리를 나타내는 列이 결합해 사람들이 줄지어 따르는 규칙, 즉 '법식, 보기'를 뜻함."
  },
  "N3-156": {
    "kanjiId": "N3-156",
    "radicalNumber": 86,
    "etymology": "회의자, 개고기를 불(灬)에 태우는 모습에서 원래 '태우다'를 뜻하다가 '그러하다'는 뜻으로 가차됨."
  },
  "N3-157": {
    "kanjiId": "N3-157",
    "radicalNumber": 170,
    "etymology": "형성자, 언덕 부(阝)와 소리를 나타내는 艮이 결합해 '한계, 한하다'는 뜻이 됨."
  },
  "N3-158": {
    "kanjiId": "N3-158",
    "radicalNumber": 162,
    "etymology": "형성자, 뜻을 나타내는 辵(辶)과 소리를 나타내는 요소가 결합해 '쫓다'는 뜻이 됨."
  },
  "N3-159": {
    "kanjiId": "N3-159",
    "radicalNumber": 30,
    "etymology": "회의자, 물건을 벌여 놓고 헤아리는 모습에서 '장사, 헤아리다'는 뜻이 됨."
  },
  "N3-160": {
    "kanjiId": "N3-160",
    "radicalNumber": 140,
    "etymology": "형성자, 풀 초(艹)와 소리를 나타내는 나뭇잎 모양의 요소가 결합해 '잎'을 뜻함."
  },
  "N3-161": {
    "kanjiId": "N3-161",
    "radicalNumber": 9,
    "etymology": "형성자, 사람 인(亻)과 소리를 나타내는 云이 결합해 사람이 말을 전달한다는 데서 '전하다'는 뜻이 됨."
  },
  "N3-162": {
    "kanjiId": "N3-162",
    "radicalNumber": 9,
    "etymology": "회의자, 사람 인(亻)과 움직일 동(動)이 결합해 사람이 움직여 일한다는 뜻을 나타내는 일본에서 만든 글자(國字)."
  },
  "N3-163": {
    "kanjiId": "N3-163",
    "radicalNumber": 59,
    "etymology": "형성자, 터럭 삼(彡)과 소리를 나타내는 开이 결합해 무늬로 드러난 겉모습, 즉 '모양'을 뜻함."
  },
  "N3-164": {
    "kanjiId": "N3-164",
    "radicalNumber": 72,
    "etymology": "형성자, 해 일(日)과 소리를 나타내는 京이 결합해 햇빛이 비추는 '볕, 경치'를 뜻함."
  },
  "N3-165": {
    "kanjiId": "N3-165",
    "radicalNumber": 140,
    "etymology": "형성자, 풀 초(艹)와 소리를 나타내는 洛이 결합해 초목의 잎이 떨어진다는 데서 '떨어지다'는 뜻이 됨."
  },
  "N3-166": {
    "kanjiId": "N3-166",
    "radicalNumber": 38,
    "etymology": "회의자, 여자 여(女)와 아들 자(子)가 결합해 어머니가 자식을 사랑스러워하는 모습에서 '좋다'는 뜻이 됨."
  },
  "N3-167": {
    "kanjiId": "N3-167",
    "radicalNumber": 162,
    "etymology": "회의자, 뜻을 나타내는 辵(辶)과 발이 뒤로 향하는 모습이 결합해 '물러나다'는 뜻이 됨."
  },
  "N3-168": {
    "kanjiId": "N3-168",
    "radicalNumber": 181,
    "etymology": "형성자, 머리 혈(頁)과 소리를 나타내는 豆가 결합해 '머리'를 뜻함."
  },
  "N3-169": {
    "kanjiId": "N3-169",
    "radicalNumber": 154,
    "etymology": "회의자, 사람과 조개 패(貝)가 결합해 사람이 재물을 짊어진 모습에서 '지다, 빚지다'는 뜻이 됨."
  },
  "N3-170": {
    "kanjiId": "N3-170",
    "radicalNumber": 85,
    "etymology": "형성자, 물 수(氵)와 소리를 나타내는 度가 결합해 '물을 건너다'는 뜻이 됨."
  },
  "N3-171": {
    "kanjiId": "N3-171",
    "radicalNumber": 37,
    "etymology": "회의자, 손에서 물건이 빠져나가는 모습을 본떠 '잃다'는 뜻이 됨."
  },
  "N3-172": {
    "kanjiId": "N3-172",
    "radicalNumber": 48,
    "etymology": "회의자, 벼 화(禾)와 왼손을 뜻하는 부분이 결합. 원래 가지런하지 않은 벼이삭을 뜻하다가 '어긋나다, 차이'로 확장됨."
  },
  "N3-173": {
    "kanjiId": "N3-173",
    "radicalNumber": 75,
    "etymology": "지사자, 나무 목(木) 위쪽에 획을 더해 나뭇가지의 '끝'을 나타냄."
  },
  "N3-174": {
    "kanjiId": "N3-174",
    "radicalNumber": 40,
    "etymology": "회의자, 집 면(宀)과 손 촌(寸)이 결합해 손으로 집을 다스리며 지킨다는 데서 '지키다'는 뜻이 됨."
  },
  "N3-175": {
    "kanjiId": "N3-175",
    "radicalNumber": 140,
    "etymology": "회의자, 풀 초(艹)와 사람이 두 손으로 머리카락을 매만지는 모습이 결합. 원래 순종한다는 뜻이었다가 '같다, 젊다'는 뜻으로 가차됨."
  },
  "N3-176": {
    "kanjiId": "N3-176",
    "radicalNumber": 115,
    "etymology": "형성자, 벼 화(禾)와 소리를 나타내는 重이 결합해 심을 볍씨, 즉 '씨, 종류'를 뜻함."
  },
  "N3-177": {
    "kanjiId": "N3-177",
    "radicalNumber": 123,
    "etymology": "회의자, 양 양(羊)과 큰 대(大)가 결합해 살진 큰 양처럼 '아름답다'는 뜻이 됨."
  },
  "N3-178": {
    "kanjiId": "N3-178",
    "radicalNumber": 30,
    "etymology": "회의자, 모을 집(亼)과 명령할 령(令)이 결합해 입으로 명령을 내리는 모습에서 '명령, 목숨'을 뜻하게 됨."
  },
  "N3-179": {
    "kanjiId": "N3-179",
    "radicalNumber": 113,
    "etymology": "형성자, 보일 시(示)와 소리를 나타내는 畐이 결합해 신에게 술을 가득 채워 바쳐 받는 '복'을 뜻함."
  },
  "N3-180": {
    "kanjiId": "N3-180",
    "radicalNumber": 74,
    "etymology": "회의자, 사람이 발돋움하여 달(月)을 바라보는 모습에서 '바라다, 바라보다'는 뜻이 됨."
  },
  "N3-181": {
    "kanjiId": "N3-181",
    "radicalNumber": 175,
    "etymology": "상형자, 새의 좌우로 펼쳐진 날개 모양을 본떠 서로 등지고 어긋난다는 데서 '아니다'는 뜻으로 가차됨."
  },
  "N3-182": {
    "kanjiId": "N3-182",
    "radicalNumber": 147,
    "etymology": "형성자, 볼 견(見)과 소리를 나타내는 雚이 결합해 '보다, 살피다'는 뜻이 됨."
  },
  "N3-183": {
    "kanjiId": "N3-183",
    "radicalNumber": 40,
    "etymology": "형성자, 집 면(宀)과 소리를 나타내는 祭가 결합해 집안 제사를 꼼꼼히 살핀다는 데서 '살피다'는 뜻이 됨."
  },
  "N3-184": {
    "kanjiId": "N3-184",
    "radicalNumber": 79,
    "etymology": "회의자, 언덕에서 돌을 떼어내는 모습에서 '층계, 단계'를 뜻하게 됨."
  },
  "N3-185": {
    "kanjiId": "N3-185",
    "radicalNumber": 75,
    "etymology": "형성자, 나무 목(木)과 소리를 나타내는 黄이 결합해 문을 가로지르는 나무 빗장, 즉 '가로'를 뜻함."
  },
  "N3-186": {
    "kanjiId": "N3-186",
    "radicalNumber": 85,
    "etymology": "형성자, 물 수(氵)와 소리를 나타내는 부분이 결합해 '깊다'는 뜻이 됨."
  },
  "N3-187": {
    "kanjiId": "N3-187",
    "radicalNumber": 102,
    "etymology": "상형자, 번개가 치는 모양을 본뜬 글자로, 원래 '펴다'는 뜻이었다가 위로 아뢴다는 데서 '아뢰다'는 뜻으로 확장됨."
  },
  "N3-188": {
    "kanjiId": "N3-188",
    "radicalNumber": 75,
    "etymology": "형성자, 나무 목(木)과 소리를 나타내는 요소가 결합. 나무의 상수리를 뜻하던 데서 '모양, 모습'으로 확장됨."
  },
  "N3-189": {
    "kanjiId": "N3-189",
    "radicalNumber": 154,
    "etymology": "형성자, 조개 패(貝)와 소리를 나타내는 才가 결합해 '재물'을 뜻함."
  },
  "N3-190": {
    "kanjiId": "N3-190",
    "radicalNumber": 85,
    "etymology": "형성자, 물 수(氵)와 소리를 나타내는 巷이 결합해 배가 드나드는 물길, 즉 '항구'를 뜻함."
  },
  "N3-191": {
    "kanjiId": "N3-191",
    "radicalNumber": 149,
    "etymology": "형성자, 말씀 언(言)과 소리를 나타내는 戠이 결합해 '알다, 식견'을 뜻함."
  },
  "N3-192": {
    "kanjiId": "N3-192",
    "radicalNumber": 30,
    "etymology": "형성자, 입 구(口)와 소리를 나타내는 乎가 결합해 '부르다'는 뜻이 됨."
  },
  "N3-193": {
    "kanjiId": "N3-193",
    "radicalNumber": 162,
    "etymology": "형성자, 뜻을 나타내는 辵(辶)과 소리를 나타내는 幸의 변형이 결합해 막힘없이 이른다는 데서 '통달하다'는 뜻이 됨."
  },
  "N3-194": {
    "kanjiId": "N3-194",
    "radicalNumber": 138,
    "etymology": "상형자, 곡식을 고르는 기구의 모양을 본떴다는 설이 있으며 '좋다, 어질다'는 뜻으로 확장됨."
  },
  "N3-195": {
    "kanjiId": "N3-195",
    "radicalNumber": 9,
    "etymology": "형성자, 사람 인(亻)과 소리를 나타내는 부분이 결합해 살펴 기다린다는 데서 '기후, 살피다'는 뜻이 됨."
  },
  "N3-196": {
    "kanjiId": "N3-196",
    "radicalNumber": 115,
    "etymology": "형성자, 벼 화(禾)와 소리를 나타내는 呈이 결합해 곡식을 되어 헤아리는 단위에서 '정도, 법도'를 뜻하게 됨."
  },
  "N3-197": {
    "kanjiId": "N3-197",
    "radicalNumber": 85,
    "etymology": "형성자, 물 수(氵)와 소리를 나타내는 요소가 결합해 물이 가득 찬다는 데서 '차다'는 뜻이 됨."
  },
  "N3-198": {
    "kanjiId": "N3-198",
    "radicalNumber": 66,
    "etymology": "회의자, 조개 패(貝)와 칠 복(攵)이 결합해 재물을 깨뜨린다는 데서 '패하다, 부서지다'는 뜻이 됨."
  },
  "N3-199": {
    "kanjiId": "N3-199",
    "radicalNumber": 9,
    "etymology": "형성자, 사람 인(亻)과 소리를 나타내는 直이 결합해 사람이 마주하여 값을 매긴다는 데서 '값'을 뜻함."
  },
  "N3-200": {
    "kanjiId": "N3-200",
    "radicalNumber": 116,
    "etymology": "회의자, 구멍 혈(穴)에서 개(犬)가 갑자기 튀어나오는 모습에서 '갑자기, 부딪치다'는 뜻이 됨."
  },
  "N4-1": {
    "kanjiId": "N4-1",
    "radicalNumber": 9,
    "etymology": "회의자, 시루에 뚜껑을 덮어 합치는 모습에서 '모이다·합치다'는 뜻이 됨."
  },
  "N4-2": {
    "kanjiId": "N4-2",
    "radicalNumber": 30,
    "etymology": "회의자, 여러 것을 하나로 모아 덮은 모습에서 '같다'는 뜻이 됨."
  },
  "N4-3": {
    "kanjiId": "N4-3",
    "radicalNumber": 6,
    "etymology": "상형자, 손에 기록 도구를 든 모습을 본떠 '일, 사무'를 뜻하게 됨."
  },
  "N4-4": {
    "kanjiId": "N4-4",
    "radicalNumber": 132,
    "etymology": "상형자, 사람의 코 모양을 본뜬 글자. 자신을 가리킬 때 코를 가리키는 습관에서 '스스로'라는 뜻으로 쓰이게 됨."
  },
  "N4-5": {
    "kanjiId": "N4-5",
    "radicalNumber": 113,
    "etymology": "형성자, 제사 시(示)와 소리를 나타내는 土가 결합. 원래 토지신을 모시는 제단을 뜻하다가 '모임, 단체'로 뜻이 확장됨."
  },
  "N4-6": {
    "kanjiId": "N4-6",
    "radicalNumber": 105,
    "etymology": "회의자, 활(弓)을 쏘는 모습에서 '(화살이) 나가다, 피어나다'는 뜻이 됨."
  },
  "N4-7": {
    "kanjiId": "N4-7",
    "radicalNumber": 125,
    "etymology": "회의자, 본래 땔감을 모아 불을 피우는 모습에서 유래했다는 설이 있으며, 후에 사람·사물을 가리키는 말로 쓰이게 됨."
  },
  "N4-8": {
    "kanjiId": "N4-8",
    "radicalNumber": 32,
    "etymology": "형성자, 흙 토(土)와 소리를 나타내는 也가 결합해 '땅'을 뜻함."
  },
  "N4-9": {
    "kanjiId": "N4-9",
    "radicalNumber": 75,
    "etymology": "상형자, 원래 종을 걸어두는 받침대의 톱니 모양을 본뜬 글자였다가 '일, 업'의 뜻으로 쓰이게 됨."
  },
  "N4-10": {
    "kanjiId": "N4-10",
    "radicalNumber": 70,
    "etymology": "상형자, 두 척의 배를 나란히 묶은 모습(또는 쟁기의 모양)을 본떴다는 설이 있으며 '모나다, 방향'을 뜻하게 됨."
  },
  "N4-11": {
    "kanjiId": "N4-11",
    "radicalNumber": 69,
    "etymology": "회의자, 도끼(斤)로 나무(木)를 베어 땔감을 만드는 모습에서 유래했고, 후에 '새롭다'는 뜻으로 가차됨."
  },
  "N4-12": {
    "kanjiId": "N4-12",
    "radicalNumber": 32,
    "etymology": "형성자, 흙 토(土)와 소리를 나타내는 昜이 결합해 '마당, 장소'를 뜻함."
  },
  "N4-13": {
    "kanjiId": "N4-13",
    "radicalNumber": 30,
    "etymology": "회의자, 둥근 솥의 모습에서 '둥글다'는 뜻이었다가 사람 수를 세는 '인원'의 뜻으로 쓰이게 됨."
  },
  "N4-14": {
    "kanjiId": "N4-14",
    "radicalNumber": 117,
    "etymology": "상형자, 사람이 땅 위에 두 팔을 벌리고 서 있는 모습을 본뜸."
  },
  "N4-15": {
    "kanjiId": "N4-15",
    "radicalNumber": 169,
    "etymology": "회의자, 빗장이 걸린 문(門)을 두 손(廾)으로 여는 모습에서 '열다'는 뜻이 됨."
  },
  "N4-16": {
    "kanjiId": "N4-16",
    "radicalNumber": 64,
    "etymology": "상형자, 다섯 손가락을 편 손의 모양을 본뜸."
  },
  "N4-17": {
    "kanjiId": "N4-17",
    "radicalNumber": 19,
    "etymology": "상형자, 팔의 힘줄 또는 쟁기의 모양을 본떠 '힘'을 뜻하게 됨."
  },
  "N4-18": {
    "kanjiId": "N4-18",
    "radicalNumber": 30,
    "etymology": "형성자, 입 구(口)와 소리를 나타내는 門이 결합해 '묻다'를 뜻함."
  },
  "N4-19": {
    "kanjiId": "N4-19",
    "radicalNumber": 9,
    "etymology": "형성자, 사람 인(亻)과 소리를 나타내는 弋이 결합해 '대신하다, 세대'를 뜻함."
  },
  "N4-20": {
    "kanjiId": "N4-20",
    "radicalNumber": 72,
    "etymology": "회의자, 해(日)와 달(月)이 나란히 있는 모습에서 '밝다'는 뜻이 됨."
  },
  "N4-21": {
    "kanjiId": "N4-21",
    "radicalNumber": 19,
    "etymology": "형성자, 힘 력(力)과 소리를 나타내는 重이 결합해 '움직이다'를 뜻함."
  },
  "N4-22": {
    "kanjiId": "N4-22",
    "radicalNumber": 8,
    "etymology": "상형자, 높이 지은 큰 건물(누각)의 모양을 본떠 '높은 언덕, 수도'를 뜻하게 됨."
  },
  "N4-23": {
    "kanjiId": "N4-23",
    "radicalNumber": 109,
    "etymology": "상형자, 사람의 눈 모양을 본뜸."
  },
  "N4-24": {
    "kanjiId": "N4-24",
    "radicalNumber": 162,
    "etymology": "형성자, 뜻을 나타내는 辵(辶, 가다)와 소리를 나타내는 甬이 결합해 '통하다'를 뜻함."
  },
  "N4-25": {
    "kanjiId": "N4-25",
    "radicalNumber": 149,
    "etymology": "상형자, 혀에서 소리가 나오는 모습을 본떠 '말'을 뜻하게 됨."
  },
  "N4-26": {
    "kanjiId": "N4-26",
    "radicalNumber": 96,
    "etymology": "형성자, 구슬 옥(王/玉)과 소리를 나타내는 里가 결합. 원래 옥의 결을 다듬는다는 뜻에서 '이치, 다스리다'로 확장됨."
  },
  "N4-27": {
    "kanjiId": "N4-27",
    "radicalNumber": 9,
    "etymology": "회의자, 사람 인(亻)과 근본 본(本)이 결합해 '사람의 근본, 몸'을 뜻함."
  },
  "N4-28": {
    "kanjiId": "N4-28",
    "radicalNumber": 102,
    "etymology": "상형자, 경계로 나뉜 밭의 모양을 본뜸."
  },
  "N4-29": {
    "kanjiId": "N4-29",
    "radicalNumber": 3,
    "etymology": "상형자, 등잔의 심지에 불이 타는 모습을 본뜬 글자로, 중심이 되는 존재라는 뜻에서 '주인'을 뜻하게 됨."
  },
  "N4-30": {
    "kanjiId": "N4-30",
    "radicalNumber": 181,
    "etymology": "형성자, 머리 혈(頁)과 소리를 나타내는 是가 결합해 원래 '이마'를 뜻하다가 글의 앞머리인 '제목'을 뜻하게 됨."
  },
  "N4-31": {
    "kanjiId": "N4-31",
    "radicalNumber": 61,
    "etymology": "회의자, 소리 음(音)과 마음 심(心)이 결합해 마음속의 소리, 즉 '생각, 뜻'을 나타냄."
  },
  "N4-32": {
    "kanjiId": "N4-32",
    "radicalNumber": 1,
    "etymology": "상형자, 꽃받침(또는 새가 날아오르는 모습)을 본뜬 글자였다가 부정을 나타내는 말로 가차됨."
  },
  "N4-33": {
    "kanjiId": "N4-33",
    "radicalNumber": 9,
    "etymology": "형성자, 사람 인(亻)과 소리를 나타내는 乍가 결합해 '만들다, 짓다'를 뜻함."
  },
  "N4-34": {
    "kanjiId": "N4-34",
    "radicalNumber": 101,
    "etymology": "상형자, 나무 통이나 종의 모양을 본떴다는 설이 있으며 '쓰다, 사용하다'는 뜻으로 쓰이게 됨."
  },
  "N4-35": {
    "kanjiId": "N4-35",
    "radicalNumber": 53,
    "etymology": "회의자, 집 엄(广)과 손(又) 등이 결합해 손으로 길이를 재는 모습에서 '자, 법도, 정도'를 뜻하게 됨."
  },
  "N4-36": {
    "kanjiId": "N4-36",
    "radicalNumber": 57,
    "etymology": "형성자, 벌레 충(虫)과 소리를 나타내는 弘의 변형이 결합. 원래 딱딱한 껍질의 벌레를 가리키다가 '강하다'는 뜻으로 쓰이게 됨."
  },
  "N4-37": {
    "kanjiId": "N4-37",
    "radicalNumber": 12,
    "etymology": "회의자, 사사로움을 뜻하는 厶를 등지는(八) 모습에서 '공평하다, 공적인'이라는 뜻이 됨."
  },
  "N4-38": {
    "kanjiId": "N4-38",
    "radicalNumber": 64,
    "etymology": "형성자, 손 수(扌)와 소리를 나타내는 寺가 결합해 '손에 쥐다, 가지다'를 뜻함."
  },
  "N4-39": {
    "kanjiId": "N4-39",
    "radicalNumber": 166,
    "etymology": "형성자, 마을 리(里)와 소리를 나타내는 予가 결합해 '들판'을 뜻함."
  },
  "N4-40": {
    "kanjiId": "N4-40",
    "radicalNumber": 9,
    "etymology": "상형자, 원래 쟁기 등의 농기구 모양을 본뜬 글자였다가 '~으로써'라는 뜻으로 가차됨."
  },
  "N4-41": {
    "kanjiId": "N4-41",
    "radicalNumber": 61,
    "etymology": "회의자, 정수리(囟, 田으로 변형됨)와 마음 심(心)이 결합해 머리와 마음으로 '생각하다'는 뜻이 됨."
  },
  "N4-42": {
    "kanjiId": "N4-42",
    "radicalNumber": 40,
    "etymology": "회의자, 집(宀) 안에 돼지(豕)가 있는 모습으로, 옛날 집 아래에 가축을 기르던 데서 '집'을 뜻하게 됨."
  },
  "N4-43": {
    "kanjiId": "N4-43",
    "radicalNumber": 1,
    "etymology": "지사자, 十(열 십) 세 개를 이어 써서 '삼십 년', 즉 한 세대를 나타내다가 '세상, 시대'를 뜻하게 됨."
  },
  "N4-44": {
    "kanjiId": "N4-44",
    "radicalNumber": 36,
    "etymology": "회의자, 고기 육(肉/夕)을 두 개 겹쳐 써서 '많다'는 뜻을 나타냄."
  },
  "N4-45": {
    "kanjiId": "N4-45",
    "radicalNumber": 77,
    "etymology": "회의자, 목표(一)를 향해 발(止)이 똑바로 나아가는 모습에서 '바르다'는 뜻이 됨."
  },
  "N4-46": {
    "kanjiId": "N4-46",
    "radicalNumber": 40,
    "etymology": "회의자, 집(宀) 안에 여자(女)가 있는 모습에서 '편안하다'는 뜻이 됨."
  },
  "N4-47": {
    "kanjiId": "N4-47",
    "radicalNumber": 170,
    "etymology": "형성자, 언덕 부(阝)와 소리를 나타내는 完이 결합해 담으로 둘러싸인 큰 건물, 즉 '집, 관청'을 뜻함."
  },
  "N4-48": {
    "kanjiId": "N4-48",
    "radicalNumber": 61,
    "etymology": "상형자, 심장의 모양을 본떠 '마음'을 뜻하게 됨."
  },
  "N4-49": {
    "kanjiId": "N4-49",
    "radicalNumber": 102,
    "etymology": "형성자, 밭 전(田)과 소리를 나타내는 介가 결합해 밭과 밭 사이의 경계, 즉 '지경, 세계'를 뜻함."
  },
  "N4-50": {
    "kanjiId": "N4-50",
    "radicalNumber": 66,
    "etymology": "회의자, 회초리를 든 손(攵)이 아이(子)에게 본받을 것을 가르치는 모습에서 '가르치다'는 뜻이 됨."
  },
  "N4-51": {
    "kanjiId": "N4-51",
    "radicalNumber": 67,
    "etymology": "상형자, 몸에 새긴 문신(무늬)의 모양을 본떠 '무늬, 글'을 뜻하게 됨."
  },
  "N4-52": {
    "kanjiId": "N4-52",
    "radicalNumber": 10,
    "etymology": "지사자, 사람의 머리를 강조해 그린 모습에서 '으뜸, 처음'을 뜻하게 됨."
  },
  "N4-53": {
    "kanjiId": "N4-53",
    "radicalNumber": 166,
    "etymology": "회의자, 사람이 짐을 지고 있는 모습에서 '무겁다'는 뜻이 됨."
  },
  "N4-54": {
    "kanjiId": "N4-54",
    "radicalNumber": 162,
    "etymology": "형성자, 뜻을 나타내는 辵(辶)과 소리를 나타내는 斤이 결합해 '가깝다'를 뜻함."
  },
  "N4-55": {
    "kanjiId": "N4-55",
    "radicalNumber": 125,
    "etymology": "형성자, 늙을 로(耂)와 소리를 나타내는 丂가 결합. 원래 '나이 든 사람'을 뜻하다가 '깊이 생각하다'는 뜻으로 확장됨."
  },
  "N4-56": {
    "kanjiId": "N4-56",
    "radicalNumber": 102,
    "etymology": "회의자, 붓(聿)으로 밭의 경계(田)를 긋는 모습에서 '긋다, 그림'을 뜻하게 됨."
  },
  "N4-57": {
    "kanjiId": "N4-57",
    "radicalNumber": 85,
    "etymology": "형성자, 물 수(氵)와 소리를 나타내는 每가 결합해 '바다'를 뜻함."
  },
  "N4-58": {
    "kanjiId": "N4-58",
    "radicalNumber": 33,
    "etymology": "회의자, 선비 사(士)와 조개 패(貝)가 결합한 형태로, 물건을 내다 판다는 뜻을 나타냄."
  },
  "N4-59": {
    "kanjiId": "N4-59",
    "radicalNumber": 111,
    "etymology": "회의자, 화살(矢)이 과녁을 맞히듯 말(口)이 정확함을 나타내 '알다'는 뜻이 됨."
  },
  "N4-60": {
    "kanjiId": "N4-60",
    "radicalNumber": 162,
    "etymology": "회의자, 사람의 머리(首)를 나타내는 부분과 걷는 것을 뜻하는 辵(辶)이 결합해 '사람이 다니는 길'을 뜻함."
  },
  "N4-61": {
    "kanjiId": "N4-61",
    "radicalNumber": 172,
    "etymology": "회의자, 새(隹)가 나무(木) 위에 모여 앉은 모습에서 '모이다'는 뜻이 됨."
  },
  "N4-62": {
    "kanjiId": "N4-62",
    "radicalNumber": 18,
    "etymology": "회의자, 뼈를 발라내는 모습과 칼(刂)이 결합해 '나누다, 헤어지다'는 뜻이 됨."
  },
  "N4-63": {
    "kanjiId": "N4-63",
    "radicalNumber": 93,
    "etymology": "형성자, 소 우(牛)와 소리를 나타내는 勿이 결합. 원래 다양한 색의 소를 가리키다가 '사물, 물건'을 뜻하게 됨."
  },
  "N4-64": {
    "kanjiId": "N4-64",
    "radicalNumber": 9,
    "etymology": "회의자, 사람 인(亻)과 관리(吏)가 결합해 명을 받아 일을 시키는 모습에서 '부리다, 시키다'는 뜻이 됨."
  },
  "N4-65": {
    "kanjiId": "N4-65",
    "radicalNumber": 30,
    "etymology": "회의자, 입 구(口)를 세 개 겹쳐 써서 여러 사람 또는 여러 물건을 나타내다가 '물건, 등급'을 뜻하게 됨."
  },
  "N4-66": {
    "kanjiId": "N4-66",
    "radicalNumber": 149,
    "etymology": "회의자, 말씀 언(言)과 열 십(十)이 결합해 수를 세어 말한다는 데서 '세다, 계산하다'는 뜻이 됨."
  },
  "N4-67": {
    "kanjiId": "N4-67",
    "radicalNumber": 78,
    "etymology": "회의자, 부서진 뼈(歹)와 사람(匕)이 결합해 사람이 죽어 뼈만 남은 모습에서 '죽다'는 뜻이 됨."
  },
  "N4-68": {
    "kanjiId": "N4-68",
    "radicalNumber": 93,
    "etymology": "형성자, 소 우(牛)와 소리를 나타내는 寺가 결합. 원래 수소 한 마리를 가리키다가 '특별하다'는 뜻으로 확장됨."
  },
  "N4-69": {
    "kanjiId": "N4-69",
    "radicalNumber": 115,
    "etymology": "형성자, 벼 화(禾)와 소리를 나타내는 厶가 결합해 개인이 거두는 곡식, 즉 '사사롭다'는 뜻이 됨."
  },
  "N4-70": {
    "kanjiId": "N4-70",
    "radicalNumber": 38,
    "etymology": "형성자, 여자 여(女)와 소리를 나타내는 台가 결합해 '시작하다'를 뜻함."
  },
  "N4-71": {
    "kanjiId": "N4-71",
    "radicalNumber": 74,
    "etymology": "회의자, 풀숲(艹) 사이로 해(日)가 떠오르고 아직 달(月)이 남아있는 새벽 모습에서 '아침'을 뜻하게 됨."
  },
  "N4-72": {
    "kanjiId": "N4-72",
    "radicalNumber": 162,
    "etymology": "형성자, 뜻을 나타내는 辵(辶)과 소리를 나타내는 軍이 결합해 '옮기다, 운반하다'는 뜻이 됨."
  },
  "N4-73": {
    "kanjiId": "N4-73",
    "radicalNumber": 120,
    "etymology": "형성자, 실 사(糸)와 소리를 나타내는 冬이 결합. 원래 실을 다 감은 끝부분을 뜻하다가 '마치다'는 뜻이 됨."
  },
  "N4-74": {
    "kanjiId": "N4-74",
    "radicalNumber": 30,
    "etymology": "회의자, 사사로울 사(厶)와 입 구(口)가 결합한 글자로, 원래 '기쁘다'는 뜻이었다가 '돈대, 무대' 등의 뜻으로 쓰이게 됨."
  },
  "N4-75": {
    "kanjiId": "N4-75",
    "radicalNumber": 53,
    "etymology": "형성자, 집 엄(广)과 소리를 나타내는 요소가 결합해 '넓다'는 뜻을 나타냄."
  },
  "N4-76": {
    "kanjiId": "N4-76",
    "radicalNumber": 9,
    "etymology": "형성자, 사람 인(亻)과 소리를 나타내는 主가 결합해 '살다, 머무르다'는 뜻이 됨."
  },
  "N4-77": {
    "kanjiId": "N4-77",
    "radicalNumber": 109,
    "etymology": "회의자, 숟가락으로 그릇에 물건을 가득 채운 모습에서 '가득 차다, 참되다'는 뜻이 됨."
  },
  "N4-78": {
    "kanjiId": "N4-78",
    "radicalNumber": 74,
    "etymology": "회의자, 손(又)에 고기(肉)를 쥔 모습에서 '가지다, 있다'는 뜻이 됨."
  },
  "N4-79": {
    "kanjiId": "N4-79",
    "radicalNumber": 30,
    "etymology": "상형자, 사람의 입 모양을 본뜸."
  },
  "N4-80": {
    "kanjiId": "N4-80",
    "radicalNumber": 42,
    "etymology": "지사자, 작은 점 몇 개로 양이 적음을 나타냄."
  },
  "N4-81": {
    "kanjiId": "N4-81",
    "radicalNumber": 102,
    "etymology": "형성자, 밭 전(田)과 소리를 나타내는 丁이 결합해 밭 사이의 두둑, 즉 구획된 땅을 뜻하다가 '마을, 동네'의 뜻으로도 쓰이게 됨."
  },
  "N4-82": {
    "kanjiId": "N4-82",
    "radicalNumber": 68,
    "etymology": "회의자, 쌀 미(米)와 말 두(斗)가 결합해 곡식을 되로 헤아리는 모습에서 '헤아리다, 재료, 요금'을 뜻하게 됨."
  },
  "N4-83": {
    "kanjiId": "N4-83",
    "radicalNumber": 48,
    "etymology": "상형자, 물건을 만들 때 쓰는 도구(자, 곱자)의 모양을 본떠 '장인, 만들다'는 뜻이 됨."
  },
  "N4-84": {
    "kanjiId": "N4-84",
    "radicalNumber": 54,
    "etymology": "회의자, 붓 율(聿)과 길게 걷는 모습(廴)이 결합해 법도를 세워 나간다는 데서 '세우다'는 뜻이 됨."
  },
  "N4-85": {
    "kanjiId": "N4-85",
    "radicalNumber": 116,
    "etymology": "형성자, 구멍 혈(穴)과 소리를 나타내는 工이 결합해 '비다, 하늘'을 뜻함."
  },
  "N4-86": {
    "kanjiId": "N4-86",
    "radicalNumber": 61,
    "etymology": "형성자, 마음 심(心)과 소리를 나타내는 及이 결합해 급히 붙잡으려는 마음에서 '급하다'는 뜻이 됨."
  },
  "N4-87": {
    "kanjiId": "N4-87",
    "radicalNumber": 77,
    "etymology": "상형자, 발자국의 모양을 본뜬 글자로, 원래 '발'을 뜻하다가 걸음을 멈춘다는 데서 '그치다'는 뜻이 됨."
  },
  "N4-88": {
    "kanjiId": "N4-88",
    "radicalNumber": 162,
    "etymology": "형성자, 뜻을 나타내는 辵(辶)과 두 손으로 물건을 받쳐 든 모습이 결합해 '보내다, 배웅하다'는 뜻이 됨."
  },
  "N4-89": {
    "kanjiId": "N4-89",
    "radicalNumber": 18,
    "etymology": "형성자, 칼 도(刀/刂)와 소리를 나타내는 七이 결합해 '끊다, 자르다'는 뜻이 됨."
  },
  "N4-90": {
    "kanjiId": "N4-90",
    "radicalNumber": 159,
    "etymology": "형성자, 수레 거(車)와 소리를 나타내는 專이 결합해 '구르다, 회전하다'는 뜻이 됨."
  },
  "N4-91": {
    "kanjiId": "N4-91",
    "radicalNumber": 112,
    "etymology": "형성자, 돌 석(石)과 소리를 나타내는 幵이 결합해 '갈다, 연마하다'는 뜻이 됨."
  },
  "N4-92": {
    "kanjiId": "N4-92",
    "radicalNumber": 157,
    "etymology": "상형자, 무릎에서 발끝까지의 다리 모양을 본떠 '발'을 뜻하게 됨."
  },
  "N4-93": {
    "kanjiId": "N4-93",
    "radicalNumber": 116,
    "etymology": "형성자, 구멍 혈(穴)과 소리를 나타내는 九가 결합해 구멍 속까지 파고든다는 데서 '깊이 연구하다'는 뜻이 됨."
  },
  "N4-94": {
    "kanjiId": "N4-94",
    "radicalNumber": 75,
    "etymology": "상형자, 나무(木) 받침 위에 방울이나 현악기가 달린 모습을 본뜬 글자로 원래 '악기, 음악'을 뜻하다가 '즐겁다'는 뜻으로 확장됨."
  },
  "N4-95": {
    "kanjiId": "N4-95",
    "radicalNumber": 156,
    "etymology": "형성자, 달릴 주(走)와 소리를 나타내는 己가 결합해 '일어나다, 시작하다'는 뜻이 됨."
  },
  "N4-96": {
    "kanjiId": "N4-96",
    "radicalNumber": 109,
    "etymology": "회의자, 양(羊)과 눈 목(目)이 결합한 형태로 원래 눈에 잘 띈다는 뜻이었다가 '붙다, 입다, 도착하다'는 뜻으로 쓰이게 됨."
  },
  "N4-97": {
    "kanjiId": "N4-97",
    "radicalNumber": 53,
    "etymology": "형성자, 집 엄(广)과 소리를 나타내는 占이 결합해 물건을 벌여 놓고 파는 곳, 즉 '가게'를 뜻함."
  },
  "N4-98": {
    "kanjiId": "N4-98",
    "radicalNumber": 104,
    "etymology": "형성자, 병들 녁(疒)과 소리를 나타내는 丙이 결합해 '병들다'를 뜻함."
  },
  "N4-99": {
    "kanjiId": "N4-99",
    "radicalNumber": 154,
    "etymology": "형성자, 조개 패(貝)와 도끼 근(斤) 두 개가 결합. 원래 저당·담보를 뜻하다가 '본바탕, 성질'의 뜻으로 확장됨."
  },
  "N4-100": {
    "kanjiId": "N4-100",
    "radicalNumber": 60,
    "etymology": "형성자, 조금 걸을 척(彳)과 소리를 나타내는 寺가 결합해 '기다리다'는 뜻이 됨."
  },
  "N4-101": {
    "kanjiId": "N4-101",
    "radicalNumber": 149,
    "etymology": "형성자, 말씀 언(言)과 소리를 나타내는 式이 결합해 말로 재능을 시험한다는 데서 '시험하다'는 뜻이 됨."
  },
  "N4-102": {
    "kanjiId": "N4-102",
    "radicalNumber": 70,
    "etymology": "회의자, 깃발과 화살이 결합해 같은 깃발 아래 모인 무리, 즉 '겨레, 일족'을 뜻하게 됨."
  },
  "N4-103": {
    "kanjiId": "N4-103",
    "radicalNumber": 167,
    "etymology": "형성자, 쇠 금(金)과 소리를 나타내는 艮이 결합해 '은'을 뜻함."
  },
  "N4-104": {
    "kanjiId": "N4-104",
    "radicalNumber": 72,
    "etymology": "회의자, 해(日)가 아직 낮게 떠 있는 모습에서 '이르다, 아침'을 뜻하게 됨."
  },
  "N4-105": {
    "kanjiId": "N4-105",
    "radicalNumber": 72,
    "etymology": "형성자, 해 일(日)과 소리를 나타내는 央이 결합해 '(빛이) 비치다'는 뜻이 됨."
  },
  "N4-106": {
    "kanjiId": "N4-106",
    "radicalNumber": 147,
    "etymology": "형성자, 볼 견(見)과 소리를 나타내는 亲이 결합. 가까이서 지켜본다는 데서 '가깝다, 어버이'를 뜻하게 됨."
  },
  "N4-107": {
    "kanjiId": "N4-107",
    "radicalNumber": 187,
    "etymology": "형성자, 말 마(馬)와 소리를 나타내는 僉이 결합. 원래 말을 시험한다는 뜻에서 '시험하다, 증험하다'로 확장됨."
  },
  "N4-108": {
    "kanjiId": "N4-108",
    "radicalNumber": 140,
    "etymology": "형성자, 풀 초(艹)와 소리를 나타내는 央이 결합해 꽃이 피어난 모습, 즉 '꽃부리, 뛰어나다'는 뜻이 됨."
  },
  "N4-109": {
    "kanjiId": "N4-109",
    "radicalNumber": 23,
    "etymology": "회의자, 상자(匚) 안에 화살(矢)을 넣은 모습으로, 다친 화살을 치료한다는 데서 '의원'을 뜻하게 됨."
  },
  "N4-110": {
    "kanjiId": "N4-110",
    "radicalNumber": 9,
    "etymology": "형성자, 사람 인(亻)과 소리를 나타내는 士가 결합해 '벼슬하다, 섬기다'는 뜻이 됨."
  },
  "N4-111": {
    "kanjiId": "N4-111",
    "radicalNumber": 28,
    "etymology": "회의자, 사람(大)이 구덩이에서 떠나는 모습에서 '가다, 떠나다'는 뜻이 됨."
  },
  "N4-112": {
    "kanjiId": "N4-112",
    "radicalNumber": 30,
    "etymology": "형성자, 입 구(口)와 소리를 나타내는 未가 결합해 '맛'을 뜻함."
  },
  "N4-113": {
    "kanjiId": "N4-113",
    "radicalNumber": 14,
    "etymology": "형성자, 덮을 멱(冖)과 소리를 나타내는 与가 결합해 물건을 그대로 옮겨 담는다는 데서 '베끼다'는 뜻이 됨."
  },
  "N4-114": {
    "kanjiId": "N4-114",
    "radicalNumber": 39,
    "etymology": "회의자, 집(宀) 안에서 아이(子)를 낳아 기르듯 글자가 계속 불어난다는 데서 '글자'를 뜻하게 됨."
  },
  "N4-115": {
    "kanjiId": "N4-115",
    "radicalNumber": 118,
    "etymology": "형성자, 대 죽(竹)과 소리를 나타내는 合이 결합. 원래 대나무 쪽지로 답신을 보낸다는 데서 '대답하다'는 뜻이 됨."
  },
  "N4-116": {
    "kanjiId": "N4-116",
    "radicalNumber": 36,
    "etymology": "형성자, 저녁 석(夕)과 소리를 나타내는 亦의 변형이 결합해 '밤'을 뜻함."
  },
  "N4-117": {
    "kanjiId": "N4-117",
    "radicalNumber": 180,
    "etymology": "지사자, 말씀 언(言)에 혀에서 소리가 나옴을 나타내는 획을 더해 '소리'를 뜻하게 됨."
  },
  "N4-118": {
    "kanjiId": "N4-118",
    "radicalNumber": 85,
    "etymology": "형성자, 물 수(氵)와 소리를 나타내는 主가 결합해 '물을 붓다, 쏟다'는 뜻이 됨."
  },
  "N4-119": {
    "kanjiId": "N4-119",
    "radicalNumber": 50,
    "etymology": "회의자, 발과 비(帚)가 결합한 형태로, 시집갈 때 살림 도구를 챙겨 돌아가는 모습에서 '돌아가다'는 뜻이 됨."
  },
  "N4-120": {
    "kanjiId": "N4-120",
    "radicalNumber": 30,
    "etymology": "회의자, 열 십(十)과 입 구(口)가 결합해 여러 대에 걸쳐 입으로 전해진 이야기, 즉 '오래되다'는 뜻이 됨."
  },
  "N4-121": {
    "kanjiId": "N4-121",
    "radicalNumber": 76,
    "etymology": "형성자, 하품 흠(欠)과 소리를 나타내는 哥가 결합해 입을 벌려 소리 내어 부른다는 데서 '노래'를 뜻함."
  },
  "N4-122": {
    "kanjiId": "N4-122",
    "radicalNumber": 154,
    "etymology": "회의자, 그물 망(罒)과 조개 패(貝)가 결합해 그물로 재물을 거두어들인다는 데서 '사다'는 뜻이 됨."
  },
  "N4-123": {
    "kanjiId": "N4-123",
    "radicalNumber": 61,
    "etymology": "형성자, 마음 심(心)과 소리를 나타내는 亜가 결합해 '나쁘다, 미워하다'는 뜻이 됨."
  },
  "N4-124": {
    "kanjiId": "N4-124",
    "radicalNumber": 31,
    "etymology": "회의자, 큰 지역(囗)과 도모할 계획을 나타내는 요소가 결합해 '그림, 도모하다'는 뜻이 됨."
  },
  "N4-125": {
    "kanjiId": "N4-125",
    "radicalNumber": 162,
    "etymology": "형성자, 뜻을 나타내는 辵(辶)과 소리를 나타내는 周가 결합해 한 바퀴 돈다는 데서 '주, 돌다'는 뜻이 됨."
  },
  "N4-126": {
    "kanjiId": "N4-126",
    "radicalNumber": 40,
    "etymology": "형성자, 집 면(宀)과 소리를 나타내는 至가 결합해 사람이 이르러 머무는 곳, 즉 '방'을 뜻함."
  },
  "N4-127": {
    "kanjiId": "N4-127",
    "radicalNumber": 77,
    "etymology": "회의자, 발자국 두 개가 겹쳐진 모습을 본떠 '걷다'는 뜻이 됨."
  },
  "N4-128": {
    "kanjiId": "N4-128",
    "radicalNumber": 182,
    "etymology": "형성자, 무릇 범(凡)과 벌레 충(虫)이 결합. 바람에 벌레가 생겨난다고 여긴 데서 '바람'을 뜻하게 됨."
  },
  "N4-129": {
    "kanjiId": "N4-129",
    "radicalNumber": 120,
    "etymology": "형성자, 실 사(糸)와 소리를 나타내는 氏가 결합해 '종이'를 뜻함."
  },
  "N4-130": {
    "kanjiId": "N4-130",
    "radicalNumber": 203,
    "etymology": "회의자, 불을 땔 때 굴뚝에 그을음이 낀 모습에서 '검다'는 뜻이 됨."
  },
  "N4-131": {
    "kanjiId": "N4-131",
    "radicalNumber": 140,
    "etymology": "형성자, 풀 초(艹)와 소리를 나타내는 化가 결합해 '꽃'을 뜻함."
  },
  "N4-132": {
    "kanjiId": "N4-132",
    "radicalNumber": 72,
    "etymology": "형성자, 해 일(日)과 풀(艹)이 결합한 모습으로, 햇볕에 풀이 돋아나는 계절인 '봄'을 뜻하게 됨."
  },
  "N4-133": {
    "kanjiId": "N4-133",
    "radicalNumber": 155,
    "etymology": "회의자, 큰 대(大)와 불 화(火)가 결합해 큰 불꽃의 색, 즉 '붉다'는 뜻이 됨."
  },
  "N4-134": {
    "kanjiId": "N4-134",
    "radicalNumber": 174,
    "etymology": "회의자, 날 생(生)과 우물 정(井)의 변형이 결합해 초목이 돋아나는 색, 즉 '푸르다'는 뜻이 됨."
  },
  "N4-135": {
    "kanjiId": "N4-135",
    "radicalNumber": 184,
    "etymology": "형성자, 밥 식(食)과 소리를 나타내는 官이 결합해 손님에게 밥을 대접하는 큰 건물, 즉 '객사, 관'을 뜻함."
  },
  "N4-136": {
    "kanjiId": "N4-136",
    "radicalNumber": 44,
    "etymology": "형성자, 주검 시(尸)와 소리를 나타내는 至가 결합해 사람이 이르러 머무는 곳, 즉 '집'을 뜻함."
  },
  "N4-137": {
    "kanjiId": "N4-137",
    "radicalNumber": 139,
    "etymology": "회의자, 사람(人)과 병부 절(㔾)이 결합한 모습으로, 원래 얼굴빛을 뜻하다가 '빛깔'로 확장됨."
  },
  "N4-138": {
    "kanjiId": "N4-138",
    "radicalNumber": 156,
    "etymology": "회의자, 사람이 팔을 휘저으며 달리는 모습과 발(止)이 결합해 '달리다'는 뜻이 됨."
  },
  "N4-139": {
    "kanjiId": "N4-139",
    "radicalNumber": 115,
    "etymology": "형성자, 벼 화(禾)와 불 화(火)가 결합. 가을에 메뚜기를 태워 없애던 데서 유래했다는 설이 있으며 '가을'을 뜻함."
  },
  "N4-140": {
    "kanjiId": "N4-140",
    "radicalNumber": 35,
    "etymology": "회의자, 원래 사람이 화려한 장식을 하고 춤추는 모습을 본뜬 글자로, 후에 계절 '여름'을 가리키게 됨."
  },
  "N4-141": {
    "kanjiId": "N4-141",
    "radicalNumber": 124,
    "etymology": "회의자, 깃 우(羽)와 흰 백(白)의 변형이 결합해 새가 날마다 날갯짓을 되풀이하며 나는 법을 익히는 모습에서 '익히다'는 뜻이 됨."
  },
  "N4-142": {
    "kanjiId": "N4-142",
    "radicalNumber": 187,
    "etymology": "형성자, 말 마(馬)와 소리를 나타내는 尺가 결합. 원래 역참에서 말을 갈아타던 데서 '역'을 뜻하게 됨."
  },
  "N4-143": {
    "kanjiId": "N4-143",
    "radicalNumber": 85,
    "etymology": "형성자, 물 수(氵)와 소리를 나타내는 羊이 결합해 '큰 바다'를 뜻함."
  },
  "N4-144": {
    "kanjiId": "N4-144",
    "radicalNumber": 70,
    "etymology": "회의자, 깃발과 사람들이 함께 있는 모습이 결합해 무리를 지어 이동하는 '군대, 나그네'를 뜻하게 됨."
  },
  "N4-145": {
    "kanjiId": "N4-145",
    "radicalNumber": 74,
    "etymology": "회의자, 배 주(舟)의 변형과 손으로 다스리는 모습이 결합. 원래 몸에 익힌다는 뜻에서 '옷, 복종하다'로 확장됨."
  },
  "N4-146": {
    "kanjiId": "N4-146",
    "radicalNumber": 36,
    "etymology": "상형자, 반달의 모양을 본떠 달이 뜨는 시각인 '저녁'을 뜻하게 됨."
  },
  "N4-147": {
    "kanjiId": "N4-147",
    "radicalNumber": 9,
    "etymology": "형성자, 사람 인(亻)과 소리를 나타내는 昔이 결합해 '빌리다'를 뜻함."
  },
  "N4-148": {
    "kanjiId": "N4-148",
    "radicalNumber": 72,
    "etymology": "형성자, 해 일(日)과 소리를 나타내는 翟이 결합해 '빛나다', 나아가 요일을 가리키는 말로 쓰이게 됨."
  },
  "N4-149": {
    "kanjiId": "N4-149",
    "radicalNumber": 184,
    "etymology": "형성자, 밥 식(食)과 하품하듯 입을 벌린 모습(欠)이 결합해 '마시다'는 뜻이 됨."
  },
  "N4-150": {
    "kanjiId": "N4-150",
    "radicalNumber": 130,
    "etymology": "상형자, 잘라낸 짐승 고기 덩어리의 모양을 본뜸."
  },
  "N4-151": {
    "kanjiId": "N4-151",
    "radicalNumber": 154,
    "etymology": "형성자, 조개 패(貝)와 소리를 나타내는 代가 결합해 재물을 대신 내어준다는 데서 '빌려주다'는 뜻이 됨."
  },
  "N4-152": {
    "kanjiId": "N4-152",
    "radicalNumber": 32,
    "etymology": "형성자, 흙 토(土)와 소리를 나타내는 尚이 결합해 흙을 높이 쌓아 지은 '큰 집'을 뜻함."
  },
  "N4-153": {
    "kanjiId": "N4-153",
    "radicalNumber": 196,
    "etymology": "상형자, 새의 모양을 본뜸."
  },
  "N4-154": {
    "kanjiId": "N4-154",
    "radicalNumber": 184,
    "etymology": "형성자, 밥 식(食)과 소리를 나타내는 反이 결합해 '밥'을 뜻함."
  },
  "N4-155": {
    "kanjiId": "N4-155",
    "radicalNumber": 19,
    "etymology": "형성자, 힘 력(力)과 소리를 나타내는 免이 결합해 '힘쓰다'는 뜻이 됨."
  },
  "N4-156": {
    "kanjiId": "N4-156",
    "radicalNumber": 15,
    "etymology": "회의자, 원래 실의 양 끝을 묶은 모습으로 '끝'을 나타내다가 한 해의 끝인 '겨울'을 뜻하게 됨."
  },
  "N4-157": {
    "kanjiId": "N4-157",
    "radicalNumber": 72,
    "etymology": "회의자, 해 일(日)과 다할 진(尽)의 변형이 결합해 해가 활동하는 시간, 즉 '낮'을 뜻함."
  },
  "N4-158": {
    "kanjiId": "N4-158",
    "radicalNumber": 140,
    "etymology": "형성자, 풀 초(艹)와 나머지 부분이 결합해 차나무 잎, 즉 '차'를 뜻함."
  },
  "N4-159": {
    "kanjiId": "N4-159",
    "radicalNumber": 57,
    "etymology": "상형자, 나무 막대에 끈을 순서대로 감아 놓은 모습을 본떠 차례를 뜻하다가 손아래 형제인 '아우'를 뜻하게 됨."
  },
  "N4-160": {
    "kanjiId": "N4-160",
    "radicalNumber": 93,
    "etymology": "상형자, 소의 머리와 뿔 모양을 본뜸."
  },
  "N4-161": {
    "kanjiId": "N4-161",
    "radicalNumber": 195,
    "etymology": "상형자, 물고기의 모양을 본뜸."
  },
  "N4-162": {
    "kanjiId": "N4-162",
    "radicalNumber": 10,
    "etymology": "회의자, 사람(儿) 위에 입 구(口)를 크게 그려 집안에서 먼저 말할 자격이 있는 손윗사람, 즉 '형'을 뜻하게 됨."
  },
  "N4-163": {
    "kanjiId": "N4-163",
    "radicalNumber": 94,
    "etymology": "상형자, 개의 옆모습을 본뜸."
  },
  "N4-164": {
    "kanjiId": "N4-164",
    "radicalNumber": 38,
    "etymology": "형성자, 여자 여(女)와 소리를 나타내는 未가 결합해 '손아래 누이'를 뜻함."
  },
  "N4-165": {
    "kanjiId": "N4-165",
    "radicalNumber": 38,
    "etymology": "형성자, 여자 여(女)와 소리를 나타내는 市(비슷한 형태)가 결합해 '손윗누이'를 뜻함."
  },
  "N4-166": {
    "kanjiId": "N4-166",
    "radicalNumber": 85,
    "etymology": "형성자, 물 수(氵)와 소리를 나타내는 요소가 결합. 원래 강 이름을 뜻하다가 나라 이름 '한'과 '한자, 한족'을 뜻하게 됨."
  },
  "N5-1": {
    "kanjiId": "N5-1",
    "radicalNumber": 72,
    "etymology": "상형자, 해의 둥근 모양을 본뜬 글자."
  },
  "N5-2": {
    "kanjiId": "N5-2",
    "radicalNumber": 1,
    "etymology": "지사자, 가로줄 하나로 '하나'라는 수를 나타냄."
  },
  "N5-3": {
    "kanjiId": "N5-3",
    "radicalNumber": 31,
    "etymology": "회의자, 나라의 영토를 나타내는 에운담(囗) 안에 옥을 지닌 임금(王)이 있음을 나타냄."
  },
  "N5-4": {
    "kanjiId": "N5-4",
    "radicalNumber": 9,
    "etymology": "상형자, 옆에서 본 사람이 서 있는 모습을 본뜸."
  },
  "N5-5": {
    "kanjiId": "N5-5",
    "radicalNumber": 51,
    "etymology": "원래 사람이 벼(禾)를 지고 가는 모습에서 온 회의자로, 한 해 농사의 수확을 나타내다가 '해'라는 뜻이 됨."
  },
  "N5-6": {
    "kanjiId": "N5-6",
    "radicalNumber": 37,
    "etymology": "상형자, 양팔과 양다리를 벌리고 서 있는 사람의 모습으로 '크다'를 나타냄."
  },
  "N5-7": {
    "kanjiId": "N5-7",
    "radicalNumber": 24,
    "etymology": "지사자, 원래 세로줄 하나로 매듭을 나타내다가 '열'을 뜻하게 됨."
  },
  "N5-8": {
    "kanjiId": "N5-8",
    "radicalNumber": 7,
    "etymology": "지사자, 가로줄 두 개로 '둘'을 나타냄."
  },
  "N5-9": {
    "kanjiId": "N5-9",
    "radicalNumber": 75,
    "etymology": "지사자, 나무(木) 뿌리 부분에 점을 찍어 '뿌리·근본'을 나타냄."
  },
  "N5-10": {
    "kanjiId": "N5-10",
    "radicalNumber": 2,
    "etymology": "지사자, 어떤 물건(囗)의 한가운데를 세로줄로 꿰뚫어 '가운데'를 나타냄."
  },
  "N5-11": {
    "kanjiId": "N5-11",
    "radicalNumber": 168,
    "etymology": "상형자, 머리카락이 긴 노인이 지팡이를 짚은 모습에서 '길다'는 뜻이 됨."
  },
  "N5-12": {
    "kanjiId": "N5-12",
    "radicalNumber": 17,
    "etymology": "회의자, 발(止)이 경계(凵) 밖으로 나가는 모습을 나타냄 (초목이 땅 위로 돋아나는 모습이라는 설도 있음)."
  },
  "N5-13": {
    "kanjiId": "N5-13",
    "radicalNumber": 1,
    "etymology": "지사자, 가로줄 세 개로 '셋'을 나타냄."
  },
  "N5-14": {
    "kanjiId": "N5-14",
    "radicalNumber": 72,
    "etymology": "형성자, 뜻을 나타내는 日과 소리를 나타내는 寺가 합쳐짐."
  },
  "N5-15": {
    "kanjiId": "N5-15",
    "radicalNumber": 144,
    "etymology": "상형자, 사거리(십자로)의 모습을 본떠 '가다·다니다'는 뜻이 됨."
  },
  "N5-16": {
    "kanjiId": "N5-16",
    "radicalNumber": 147,
    "etymology": "회의자, 사람(儿) 위에 눈(目)을 강조해 그려 '보다'는 뜻을 나타냄."
  },
  "N5-17": {
    "kanjiId": "N5-17",
    "radicalNumber": 74,
    "etymology": "상형자, 초승달의 모양을 본뜸."
  },
  "N5-18": {
    "kanjiId": "N5-18",
    "radicalNumber": 18,
    "etymology": "회의자, 칼(刀)로 물건을 나누는 모습(八)을 그려 '나누다'는 뜻을 나타냄."
  },
  "N5-19": {
    "kanjiId": "N5-19",
    "radicalNumber": 60,
    "etymology": "회의자, 걸을 척(彳)과 발이 실에 묶여 뒤처짐(幺+夂)을 나타내 '뒤'를 뜻함."
  },
  "N5-20": {
    "kanjiId": "N5-20",
    "radicalNumber": 18,
    "etymology": "원래 배(舟)가 발(止)과 함께 나아가는 모습이었다가, 자형이 바뀌며 칼(刀→刂)이 더해진 것으로 '앞'을 뜻하게 됨."
  },
  "N5-21": {
    "kanjiId": "N5-21",
    "radicalNumber": 100,
    "etymology": "상형자, 땅 위로 풀(屮)이 돋아나는 모습을 본떠 '나다·살다'는 뜻이 됨."
  },
  "N5-22": {
    "kanjiId": "N5-22",
    "radicalNumber": 7,
    "etymology": "지사자, 하늘과 땅(二) 사이에서 무언가 교차하는 모습(×)으로 '다섯'을 나타냄."
  },
  "N5-23": {
    "kanjiId": "N5-23",
    "radicalNumber": 169,
    "etymology": "회의자, 문(門) 틈 사이로 해(日)가 비치는 모습에서 '사이'를 뜻함 (원래는 달 月이었다가 日로 바뀜)."
  },
  "N5-24": {
    "kanjiId": "N5-24",
    "radicalNumber": 1,
    "etymology": "지사자, 기준선 위에 점(짧은 획)을 찍어 '위'를 나타냄."
  },
  "N5-25": {
    "kanjiId": "N5-25",
    "radicalNumber": 75,
    "etymology": "전통적으로 나무(木) 사이로 해(日)가 떠오르는 모습이라 설명되나, 갑골문 자형을 근거로 양끝을 묶은 자루 모양이라는 해석도 있음."
  },
  "N5-26": {
    "kanjiId": "N5-26",
    "radicalNumber": 31,
    "etymology": "지사자, 원래는 가로줄 네 개였다가 코에서 숨이 갈라져 나가는 모습(囗+八)을 본뜬 자형으로 바뀌어 '넷'을 나타냄."
  },
  "N5-27": {
    "kanjiId": "N5-27",
    "radicalNumber": 9,
    "etymology": "회의자, 사람(人)이 무언가를 머금은(一) 모습에서 '바로 지금'이라는 뜻이 됨."
  },
  "N5-28": {
    "kanjiId": "N5-28",
    "radicalNumber": 167,
    "etymology": "형성자, 흙(土) 속에 파묻힌 쇳덩이와 소리를 나타내는 부분이 합쳐져 '쇠·금'을 뜻함."
  },
  "N5-29": {
    "kanjiId": "N5-29",
    "radicalNumber": 5,
    "etymology": "지사자, 팔을 구부린 모습을 본떠 '아홉'이라는 수를 나타냄 (자형의 유래는 명확히 밝혀지지 않음)."
  },
  "N5-30": {
    "kanjiId": "N5-30",
    "radicalNumber": 11,
    "etymology": "상형자, 뾰족한 물건이 안으로 들어가는 모습을 본뜸."
  },
  "N5-31": {
    "kanjiId": "N5-31",
    "radicalNumber": 39,
    "etymology": "회의자, 아이(子)가 두 손으로 지붕(冖) 아래에서 배우는 모습(원자형 學)을 간략화함."
  },
  "N5-32": {
    "kanjiId": "N5-32",
    "radicalNumber": 189,
    "etymology": "상형자, 높이 지은 누각·망루의 모습을 본뜸."
  },
  "N5-33": {
    "kanjiId": "N5-33",
    "radicalNumber": 13,
    "etymology": "圓의 약자로, 에운담(囗→冂) 안에 둥근 도구가 있어 '둥글다'는 뜻이었다가 일본에서 화폐 단위로도 쓰임."
  },
  "N5-34": {
    "kanjiId": "N5-34",
    "radicalNumber": 39,
    "etymology": "상형자, 강보에 싸인 아기의 모습을 본뜸."
  },
  "N5-35": {
    "kanjiId": "N5-35",
    "radicalNumber": 36,
    "etymology": "회의자, 저녁(夕)에 거북 껍질로 점(卜)을 치던 관습에서, 원래 점치던 때가 아닌 때를 가리켜 '바깥'을 뜻하게 됨."
  },
  "N5-36": {
    "kanjiId": "N5-36",
    "radicalNumber": 12,
    "etymology": "지사자, 두 갈래로 나뉜 모습을 본떠 '여덟'을 나타냄."
  },
  "N5-37": {
    "kanjiId": "N5-37",
    "radicalNumber": 12,
    "etymology": "자형의 유래가 명확하지 않으며, 가차되어 '여섯'이라는 수를 나타냄."
  },
  "N5-38": {
    "kanjiId": "N5-38",
    "radicalNumber": 1,
    "etymology": "지사자, 기준선 아래에 점(짧은 획)을 찍어 '아래'를 나타냄."
  },
  "N5-39": {
    "kanjiId": "N5-39",
    "radicalNumber": 9,
    "etymology": "원래 익은 보리 이삭의 모습을 본뜬 상형자였는데, 소리가 같아 '오다'라는 뜻으로 가차되어 쓰이게 됨."
  },
  "N5-40": {
    "kanjiId": "N5-40",
    "radicalNumber": 84,
    "etymology": "氣의 약자로, 원래 피어오르는 수증기·구름의 모습을 본뜬 상형자에서 비롯됨."
  },
  "N5-41": {
    "kanjiId": "N5-41",
    "radicalNumber": 42,
    "etymology": "상형자, 작은 점(모래알) 세 개를 그려 '작다'는 뜻을 나타냄."
  },
  "N5-42": {
    "kanjiId": "N5-42",
    "radicalNumber": 1,
    "etymology": "원래 무언가를 자르는 모습에서 비롯됐으며 가차되어 '일곱'이라는 수를 나타냄."
  },
  "N5-43": {
    "kanjiId": "N5-43",
    "radicalNumber": 46,
    "etymology": "상형자, 봉우리가 솟은 산의 모습을 본뜸."
  },
  "N5-44": {
    "kanjiId": "N5-44",
    "radicalNumber": 149,
    "etymology": "형성자, 뜻을 나타내는 言과 소리를 나타내는 舌이 합쳐짐."
  },
  "N5-45": {
    "kanjiId": "N5-45",
    "radicalNumber": 38,
    "etymology": "상형자, 두 손을 모으고 무릎을 꿇은 여성의 모습을 본뜸."
  },
  "N5-46": {
    "kanjiId": "N5-46",
    "radicalNumber": 21,
    "etymology": "회의자, 두 사람이 서로 등을 지고 있는 모습(背의 원자)에서, 집이 남쪽을 향할 때 등지는 방향인 '북쪽'을 뜻하게 됨."
  },
  "N5-47": {
    "kanjiId": "N5-47",
    "radicalNumber": 24,
    "etymology": "원래 절굿공이 모양을 본뜬 상형자였는데, 가차되어 십이지의 일곱째(말)와 정오를 뜻하게 됨."
  },
  "N5-48": {
    "kanjiId": "N5-48",
    "radicalNumber": 106,
    "etymology": "一과 白(소리를 나타냄)이 합쳐진 형성자로 '백'을 나타냄."
  },
  "N5-49": {
    "kanjiId": "N5-49",
    "radicalNumber": 72,
    "etymology": "회의자, 붓(聿)으로 말한 것을 적는다는 데서 '쓰다'는 뜻이 됨."
  },
  "N5-50": {
    "kanjiId": "N5-50",
    "radicalNumber": 10,
    "etymology": "회의자, 사람(儿) 위에 발을 그려 남보다 앞서 나아감을 나타냄."
  },
  "N5-51": {
    "kanjiId": "N5-51",
    "radicalNumber": 30,
    "etymology": "회의자, 저녁(夕) 어두울 때 자기 이름을 입(口)으로 말해 알린다는 데서 '이름'을 뜻함."
  },
  "N5-52": {
    "kanjiId": "N5-52",
    "radicalNumber": 47,
    "etymology": "상형자, 물이 굽이쳐 흐르는 하천의 모습을 본뜸."
  },
  "N5-53": {
    "kanjiId": "N5-53",
    "radicalNumber": 24,
    "etymology": "지사자, 사람 인(人)에 가로줄을 더해 '천'이라는 수를 나타냄."
  },
  "N5-54": {
    "kanjiId": "N5-54",
    "radicalNumber": 85,
    "etymology": "상형자, 물이 흐르는 모습을 본뜸."
  },
  "N5-55": {
    "kanjiId": "N5-55",
    "radicalNumber": 24,
    "etymology": "회의자, 소(牛)를 반으로 나눈다(八)는 데서 '반쪽'을 뜻함."
  },
  "N5-56": {
    "kanjiId": "N5-56",
    "radicalNumber": 102,
    "etymology": "회의자, 밭(田)에서 힘(力)을 쓰는 사람이라는 데서 '사내'를 뜻함."
  },
  "N5-57": {
    "kanjiId": "N5-57",
    "radicalNumber": 146,
    "etymology": "상형자, 해가 질 때 새가 둥지에 깃드는 모습을 본떠 '서쪽'을 나타냄."
  },
  "N5-58": {
    "kanjiId": "N5-58",
    "radicalNumber": 173,
    "etymology": "형성자, 비(雨)와 번개가 치는 모습이 합쳐져 원래 '번개'를 뜻하다가 '전기'라는 뜻으로도 쓰임."
  },
  "N5-59": {
    "kanjiId": "N5-59",
    "radicalNumber": 75,
    "etymology": "형성자, 나무(木)와 소리를 나타내는 交가 합쳐짐 (원래 나무로 만든 울타리·형틀을 뜻하다가 '학교'로 쓰이게 됨)."
  },
  "N5-60": {
    "kanjiId": "N5-60",
    "radicalNumber": 149,
    "etymology": "형성자, 뜻을 나타내는 言과 소리를 나타내는 吾가 합쳐져 '말씀'을 뜻함."
  },
  "N5-61": {
    "kanjiId": "N5-61",
    "radicalNumber": 32,
    "etymology": "상형자, 땅 위에 흙무더기가 쌓인 모습을 본뜸."
  },
  "N5-62": {
    "kanjiId": "N5-62",
    "radicalNumber": 75,
    "etymology": "상형자, 뿌리·줄기·가지가 있는 나무의 모습을 본뜸."
  },
  "N5-63": {
    "kanjiId": "N5-63",
    "radicalNumber": 128,
    "etymology": "형성자, 뜻을 나타내는 耳와 소리를 나타내는 門이 합쳐져 '듣다'는 뜻이 됨."
  },
  "N5-64": {
    "kanjiId": "N5-64",
    "radicalNumber": 184,
    "etymology": "회의자, 밥그릇에 뚜껑을 덮은 모습을 본떠 '밥·먹다'는 뜻이 됨."
  },
  "N5-65": {
    "kanjiId": "N5-65",
    "radicalNumber": 159,
    "etymology": "상형자, 위에서 내려다본 수레바퀴와 굴대의 모습을 본뜸."
  },
  "N5-66": {
    "kanjiId": "N5-66",
    "radicalNumber": 9,
    "etymology": "원래 사람(人/亻)이 짐을 짊어진 모습(荷의 원자)이었다가, 가차되어 '무엇'이라는 뜻으로 쓰이게 됨."
  },
  "N5-67": {
    "kanjiId": "N5-67",
    "radicalNumber": 51,
    "etymology": "원래 악기(종·북 종류)의 모습을 본뜬 상형자였는데 가차되어 '남쪽'을 뜻하게 됨."
  },
  "N5-68": {
    "kanjiId": "N5-68",
    "radicalNumber": 1,
    "etymology": "萬의 약자로, 원래 전갈의 모습을 본뜬 상형자였다가 가차되어 '만'이라는 수를 나타냄."
  },
  "N5-69": {
    "kanjiId": "N5-69",
    "radicalNumber": 80,
    "etymology": "每의 약자로, 비녀를 꽂아 머리를 꾸민 여자(母 계열)의 모습에서 '매양·마다'라는 뜻으로 쓰이게 됨."
  },
  "N5-70": {
    "kanjiId": "N5-70",
    "radicalNumber": 106,
    "etymology": "상형자, 엄지손톱 또는 촛불의 흰 빛 등을 본떴다는 여러 설이 있으며 '희다'는 뜻을 나타냄."
  },
  "N5-71": {
    "kanjiId": "N5-71",
    "radicalNumber": 37,
    "etymology": "지사자, 사람(大)의 머리 위(一)를 가리켜 '하늘'을 나타냄."
  },
  "N5-72": {
    "kanjiId": "N5-72",
    "radicalNumber": 80,
    "etymology": "상형자, 두 손을 모은 여자(女)의 모습에 젖가슴을 나타내는 두 점을 더해 '어머니'를 나타냄."
  },
  "N5-73": {
    "kanjiId": "N5-73",
    "radicalNumber": 86,
    "etymology": "상형자, 타오르는 불꽃의 모습을 본뜸."
  },
  "N5-74": {
    "kanjiId": "N5-74",
    "radicalNumber": 30,
    "etymology": "회의자, 손(又)과 입(口)을 그려, 오른손으로 밥을 먹으며 남을 돕는다는 데서 '오른쪽·돕다'는 뜻이 됨."
  },
  "N5-75": {
    "kanjiId": "N5-75",
    "radicalNumber": 149,
    "etymology": "형성자, 뜻을 나타내는 言과 소리를 나타내는 売가 합쳐짐."
  },
  "N5-76": {
    "kanjiId": "N5-76",
    "radicalNumber": 29,
    "etymology": "회의자, 손(又) 두 개를 나란히 그려 서로 손을 맞잡고 돕는 사이인 '벗'을 나타냄."
  },
  "N5-77": {
    "kanjiId": "N5-77",
    "radicalNumber": 48,
    "etymology": "회의자, 왼손(손의 변형)과 도구를 뜻하는 工을 그려, 왼손으로 일을 돕는다는 데서 '왼쪽'을 나타냄."
  },
  "N5-78": {
    "kanjiId": "N5-78",
    "radicalNumber": 9,
    "etymology": "회의자, 사람(人/亻)이 나무(木) 그늘 아래에서 쉬는 모습을 본뜸."
  },
  "N5-79": {
    "kanjiId": "N5-79",
    "radicalNumber": 88,
    "etymology": "상형자, 손에 도끼·회초리 같은 도구를 쥔 모습을 본떠 집안을 다스리는 '아버지'를 나타냄."
  },
  "N5-80": {
    "kanjiId": "N5-80",
    "radicalNumber": 173,
    "etymology": "상형자, 하늘(一)에서 빗방울이 떨어지는 모습을 본뜸."
  }
}
